#pragma once

#include "types.h"

//t6/code/src_noserver/ui/ui_atoms.cpp
void UI_DrawHandlePic(;
void UI_DrawHandlePicRotated(;
void UI_DrawHandlePicFramed(;
double UI_LoadBarProgress_LoadObj();
double UI_LoadBarProgress_FastFile();
void UI_ForceFullLoadBar(bool force);
void UI_DrawLoadBar(;
void UI_FillRectPhysical(float x, float y, float width, float height, const vec4_t *color);
void UI_FillRect(;
void UI_DrawSpinner(;
void UI_DrawSpinnerLoadbar(;

//t6/code/src_noserver/ui/ui_codtv.cpp
void UI_Codtv_Init();
codtvType_e UI_Codtv_GetType(const char *typeString);
codtvImageCategory_e UI_Codtv_GetImageCategory(const char *categoryString);
void UI_Codtv_FilterAll(codtvDWContent_t *content);
void UI_Codtv_FilterSelf(codtvDWContent_t *content);
void UI_Codtv_FilterOtherPlayer(codtvDWContent_t *content);
void UI_Codtv_FilterFriends(codtvDWContent_t *content);
void UI_Codtv_FilterPooled(codtvDWContent_t *content);
void UI_Codtv_FilterUser(codtvDWContent_t *content);
void UI_Codtv_FilterFilms(codtvDWContent_t *content);
void UI_Codtv_FilterClips(codtvDWContent_t *content);
void UI_Codtv_FilterScreenshots(codtvDWContent_t *content);
void UI_Codtv_FilterCustomGames(codtvDWContent_t *content);
void UI_Codtv_FilterEmblems(codtvDWContent_t *content);
void UI_Codtv_FilterBookmarked(codtvDWContent_t *content);
void UI_Codtv_FilterVictories(codtvDWContent_t *content);
void UI_Codtv_FilterHighestRated(codtvDWContent_t *content);
void UI_Codtv_FilterTrending(codtvDWContent_t *content);
void UI_Codtv_FilterStaffPick(codtvDWContent_t *content);
void UI_Codtv_FilterClan(codtvDWContent_t *content);
void UI_Codtv_FilterLeagueTeam(codtvDWContent_t *content);
void UI_Codtv_FilterIngameStore(codtvDWContent_t *content);
char UI_Codtv_ReadFolderContentDW(codtvFolder_t *folder);
char UI_Codtv_ReadFolderContentVideo(codtvFolder_t *folder);
char UI_Codtv_ReadCustomButtonAction(codtvFolder_t *folder);
char UI_Codtv_ReadFolderContent(codtvFolder_t *folder);
char UI_Codtv_ReadFolderType(codtvFolder_t *folder);
char UI_Codtv_ReadFolderImage(codtvFolder_t *folder);
char UI_Codtv_ReadFolderRef(codtvFolder_t *folder);
char UI_Codtv_ReadFolderName(codtvFolder_t *folder);
char UI_Codtv_ReadFolder(codtvFolder_t *parent);
char UI_Codtv_ReadRootVersion();
char UI_Codtv_ParseHeader();
bool UI_Codtv_ParseMenuFile(unsigned __int8 *buffer, jsmntok_t *parseTokens);
void UI_Codtv_Parse(unsigned __int8 *buffer);

//t6/code/src_noserver/ui/ui_emblem.cpp
emblemDownloadData_t *UI_EmblemPool_Get(unsigned __int64 fileID);
void UI_EmblemClampLayer(CompositeEmblemLayer *layer);
void UI_DrawCustomEmblem(UIContextIndex_t contextIndex, const rectDef_s *rect, const vec4_t *color);
void UI_DrawEmblemSelector(;
void UI_DrawEmblemIconThumbnail(UIContextIndex_t contextIndex, const rectDef_s *rect, const vec4_t *color);
void UI_EmblemUpdate();
int UI_EmblemGetSelectedLayer();
bool UI_EmblemCanOutlineLayer(int layer);
BOOL UI_EmblemCanDuplicateLayer(ControllerIndex_t controllerIndex);
void UI_EmblemDuplicate_f();
const GfxViewParms *UI_EmblemGetLayerName(int layer);
__int16 UI_EmblemGetSelectedBackgroundID();
const char *UI_EmblemGetStateDisplay(ControllerIndex_t controllerIndex, int idx);
char *UI_EmblemGetCategoryDisplay(ControllerIndex_t controllerIndex, int idx);
int UI_EmblemGetFilterCount(ControllerIndex_t controllerIndex, int state, int category);
__int16 UI_EmblemGetFilterIconID(ControllerIndex_t controllerIndex, int state, int category, int index);
bool UI_EmblemUpload_SetMetada(;
void UI_EmblemUploadToSlotSuccess(const ControllerIndex_t controllerIndex, unsigned __int64 fileID);
void UI_EmblemUploadToSlotFailure(const ControllerIndex_t controllerIndex);
void UI_EmblemUploadToSlot(const ControllerIndex_t controllerIndex, int slot, bool setToProfile);
void UI_EmblemSetName(const char *name);
void UI_EmblemSetDescription(const char *description);
void UI_EmblemClearUploadInfo_f();
void UI_EmblemSelect_f();
void UI_EmblemReset_f();
void UI_EmblemClear_f();
void UI_EmblemDelete_f();
void UI_EmblemClearAll_f();
void UI_EmblemClearClipboard_f();
void UI_EmblemRotate_f();
void UI_EmblemMove_f();
void UI_EmblemScale_f();
void UI_EmblemIcon_f();
void UI_EmblemSetSelectedLayerIconId_f();
void UI_EmblemSetEmptyBoxIconId_f();
void UI_EmblemPalette_f();
void UI_EmblemOutline_f();
void UI_EmblemToggleOutline_f();
void UI_EmblemFlip_f();
void UI_EmblemToggleFlip_f();
void UI_EmblemLayerIncreaseOpacity_f();
void UI_EmblemLayerDecreaseOpacity_f();
void UI_EmblemLayerSetOpacity_f();
void UI_EmblemSetScaleMode_f();
void UI_EmblemMoveLayer(ControllerIndex_t controllerIndex, int targetz);
void UI_EmblemSetLayerColorRGB_f();
void UI_EmblemSetSelectedRecentColor_f();
void UI_EmblemSetRecentColorRGBA_f();
void UI_EmblemSetRGBTweakedColor_f();
void UI_EmblemMoveLayer_f();
void UI_EmblemMoveLayerRelative_f();
void UI_EmblemCopy_f();
void UI_EmblemCopyLayer_f();
void UI_EmblemPasteLayer_f();
void UI_EmblemRevertColorChanges_f();
void UI_EmblemBeginEdit_f();
void UI_EmblemEndEdit_f();
void UI_EmblemSelectBackground_f();
void UI_EmblemDump_f();
;
void UI_EmblemSetAsDefault_f();
void UI_EmblemSetFromDefault_f();
void UI_EmblemUploadToSlot_f();
void UI_EmblemLoadFromFile_f();
void UI_EmblemSetLeagueIdentity_f();
void UI_EmblemSetClanIdentity_f();
void UI_EmblemMoveUpRepeatEnabled_f();
void UI_EmblemMoveDownRepeatEnabled_f();
void UI_EmblemMoveLeftRepeatEnabled_f();
void UI_EmblemMoveRightRepeatEnabled_f();
void UI_EmblemScaleUpRepeatEnabled_f();
void UI_EmblemScaleDownRepeatEnabled_f();
void UI_EmblemRotateLeftRepeatEnabled_f();
void UI_EmblemRotateRightRepeatEnabled_f();
void UI_EmblemRepeatBttnsLooseFocus_f();
void UI_EmblemSetPosition_f();
void UI_EmblemShowFileID_f();
vec4_t *UI_GetSlectedSwatchElementColor(vec4_t *result, int row, int column, int totalRows, int totalColumns);
void UI_EmblemSetLayerColorFromSwatch_f();
void UI_EmblemRegisterCmds();

//t6/code/src_noserver/ui/ui_feeders.cpp
void UI_BuildPlayerList(LocalClientNum_t localClientNum);
int UI_FeederCount(;
void UI_FeederItemColor(;
void UI_ResetSelectedPlayerXuid();
void UI_OverrideCursorPos_Gamemodes(UIContextIndex_t contextIndex, listBoxDef_s *listPtr);
void UI_OverrideCursorPos_Servers(;
char UI_OverrideKeyPress(;
void UI_OverrideCursorPos_DynamicMenu(UIContextIndex_t contextIndex, listBoxDef_s *listPtr);
// int UI_OverrideCursorPos_Default@<eax>(;
void UI_OverrideCursorPos(LocalClientNum_t localClientNum, UIContextIndex_t contextIndex, itemDef_s *item);
void UI_FeederSelection(;
bool UI_FeederDataExtended_DynamicMenu(;
bool UI_FeederDataExtended(;
void UI_AddToFeeder(itemDef_s *item, const char *eventName, int argCount, const char **args);
void UI_AddToFeederExtended(;
void UI_ChangeRowStatus(itemDef_s *item, int rowToChange, int newStatus);
void UI_ClearFeeder(UIContextIndex_t contextIndex, itemDef_s *item, bool resetCursorPos);
bool UI_FeederData(;
const char *UI_FeederItemText_DynamicMenu(;
void UI_RaiseFeederEvent(LocalClientNum_t localClientNum, itemDef_s *item, const char *eventName);
// const char *UI_FeederItemText@<eax>(;

//t6/code/src_noserver/ui/ui_friends.cpp
void UI_FriendsRegisterDvars();

//t6/code/src_noserver/ui/ui_keyboard.cpp
void UI_SetActiveKeyboardType(int keyboardType);
void UI_Keyboard_ClanTagEntered(LocalClientNum_t localClientNum, const char *clanTag);
BOOL UI_Keyboard_ParseEmail(const char *address);
void UI_Keyboard_CheckValidEmail();
void UI_Keyboard_EmailEntry_f();
void UI_KeyboardComplete(LocalClientNum_t localClientNum);
void UI_Keyboard_Complete_f();
void UI_Keyboard_Cancel_f();
void UI_Keyboard_New_f();

//#include "ui/ui_local.h"

//t6/code/src_noserver/ui/ui_localvars.cpp
void UILocalVar_Init(UILocalVarContext *context);
void UILocalVar_Shutdown(UILocalVarContext *context);
char UILocalVar_FindLocation(UILocalVarContext *context, const char *name, unsigned int *hashForName);
const UILocalVar *UILocalVar_Find(UILocalVarContext *context, const char *name);
UILocalVar *UILocalVar_FindOrCreate(UILocalVarContext *context, const char *name);
BOOL UILocalVar_GetBool(const UILocalVar *var);
// UILocalVar::<unnamed_type_u> UILocalVar_GetInt(const UILocalVar *var);
double UILocalVar_GetFloat(const UILocalVar *var);
char *UILocalVar_GetString(const UILocalVar *var, char *stringBuf, int size);
void UILocalVar_SetBool(const UILocalVar *var, bool b);
void UILocalVar_SetInt(const UILocalVar *var, int i);
void UILocalVar_SetFloat(const UILocalVar *var, float f);
void UILocalVar_SetString(const UILocalVar *var, const char *s);

//t6/code/src_noserver/ui/ui_main.cpp
UiContext *UI_UIContext_GetInfo(UIContextIndex_t contextIndex);
UiContext *UI_GetInfo(LocalClientNum_t localClientNum);
UILocalVarContext *UI_UIContext_GetLocalVarsContext(UIContextIndex_t contextIndex);
const char *UI_GetMonthAbbrev(int month);
void TRACK_ui_main();
void UI_RegisterDvars();
void UI_AssetCache();
char *GetMenuBuffer_LoadObj(const char *filename);
XModelPiece *GetMenuBuffer_FastFile(const char *filename);
char *UI_GetMenuBuffer();
void UI_GameModeHistory_AddMatchHistory();
void UI_GameModeHistory_Clear();
void UI_DrawSides(;
void UI_DrawTopBottom(;
void UI_DrawRect(;
void UI_DrawHighlightRect(;
int UI_TextWidth(LocalClientNum_t localClientNum, const char *text, int maxChars, Font_s *font, float scale);
int UI_TextHeight(Font_s *font, float scale);
void UI_DrawTextRotated(;
void UI_DrawTextWithGlow(;
void UI_DrawTextNoSnap(;
void UI_DrawTextWithCursor(;
Font_s *UI_GetFontHandleDefault(float scale);
Font_s *UI_GetFontHandle(const ScreenPlacement *scrPlace, int fontEnum, float scale);
void UI_UpdateTime(LocalClientNum_t localClientNum, int realtime);
bool UI_ShouldDrawBuildNumber(LocalClientNum_t localClientNum);
void UI_Shutdown(LocalClientNum_t localClientNum);
MenuList *Load_ScriptMenuInternal(const char *pszMenu, int imageTrack);
// int Load_ScriptMenu@<eax>(int a1@<edx>, const char *a2@<ecx>, LocalClientNum_t localClientNum);
void UI_VerifyLanguage();
bool UI_GetOpenOrCloseMenuOnDvarArgs(;
bool UI_DvarValueTest(const char *cmd, const char *dvarName, const char *testValue, bool wantMatch);
void UI_OpenMenuOnDvar(;
void UI_CloseMenuOnDvar(;
void UI_RunMenuScript(;
void UI_Pause(LocalClientNum_t localClientNum, int b);
void UI_UpdateMouseScreenPosition(LocalClientNum_t localClientNum, int x, int y);
void UI_MouseEvent(LocalClientNum_t localClientNum);
int UI_GetActiveMenu(LocalClientNum_t localClientNum);
int UI_IsFullscreen(LocalClientNum_t localClientNum);
double UI_GetBlurRadius(LocalClientNum_t localClientNum);
const char *UI_SafeTranslateString(const char *reference);
void UI_FormatStringWithCommas(char *outputString, int stringLength, unsigned __int64 value);
void UI_FilterStringForButtonAnimation(char *str, unsigned int strMaxSize);
void UI_ReplaceConversions(;
void UI_CloseFocusedMenu(LocalClientNum_t localClientNum);
bool Menu_IsMenuOpenAndVisible(const LocalClientNum_t localClientNum, const char *menuName);
void UI_ClosePopupScriptMenu(LocalClientNum_t localClientNum, bool allowResponse);
bool UI_AllowScriptMenuResponse(LocalClientNum_t localClientNum);
void UI_CloseInGameMenu(LocalClientNum_t localClientNum);
bool CheckCurrentChar(char charToCheck, const char *testChars);
;
bool UI_CheckClanTagAllowed(ControllerIndex_t controllerIndex, const char *clanTag);
void UI_SetClanName(ControllerIndex_t localControllerIndex, const char *clanName);
void UI_SetClanNameCmd();
void UI_CheckClanName();
void UI_CheckClanNameCmd();
int UI_OwnerDrawWidth(LocalClientNum_t localClientNum, int ownerDraw, Font_s *font, float scale);
void UI_DrawLocalTalking(;
int UI_GetTalkerClientNum(LocalClientNum_t localClientNum, UIContextIndex_t contextIndex, const int num);
void UI_DrawPartyStatus(;
char *GetXpLockDescription(const LocalClientNum_t localClientNum, const int playlistId);
void UI_DrawScrollingTextLong(;
void UI_DrawScrollingTextMOTD(;
void UI_DrawControllerIcon(;
void UI_OwnerDraw(;
void UI_InitUIInfos();
void UI_InitOnceForAllClients();
void UI_Init(LocalClientNum_t localClientNum);
bool UI_KeyEvent_CancelButtonPressed(;
bool UI_MenuInputAllowedForLocalClientNum(LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *menu);
bool UI_KeyEvent_IsLocalClientInputAllowedForMenu(;
char UI_HandleLocalClientInput(;
void UI_CloseAll(LocalClientNum_t localClientNum);
void UI_UIContext_OpenToastPopup(;
void UI_OpenErrorPopup();
void UI_OpenMenu(LocalClientNum_t localClientNum, const char *menuName);
void UI_CloseMenu(LocalClientNum_t localClientNum, const char *menuName);
void UI_CloseFromMenuToTopOfStack(LocalClientNum_t localClientNum, const char *menuName);
void UI_OpenToastPopup(;
void UI_LoadIngameMenus(LocalClientNum_t localClientNum);
char *UI_ToUpper(const char *sourceString);
bool UI_KeysBypassMenu(const LocalClientNum_t localClientNum);
void UI_DrawTextPadding(;
void UI_DrawText(;
void UI_DrawMouseCursor(LocalClientNum_t localClientNum);
const char *UI_GetMapDisplayName(const char *pszMap);
const char *UI_GetMapDisplayNameFromPartialLoadNameMatch(const char *mapName, int *mapLoadNameLen);
const char *UI_GetGameTypeDisplayName(const char *pszGameType, const char *pszMap);
void UI_ShowAcceptInviteWarning(LocalClientNum_t localClientNum);
char *UI_ReplaceConversionStrings(const char *sourceString, int numStrings, const char **replaceStrings);
char *UI_ReplaceConversionInts(const char *sourceString, int numInts, int *replaceInts);
void UI_DrawKeyBindStatus(;
void UI_DrawTalkerNum(;
void UI_DrawReservedSlots(;
void UI_DrawLoggedInUser(;
void UI_DrawLoggedInUserName(;
void UI_OwnerDrawText(;
void UI_KeyEvent(LocalClientNum_t localClientNum, int key, int down);
void UI_DrawBuildNumber(LocalClientNum_t localClientNum, const UIContextIndex_t contextIndex);
void UI_DrawSessionAndGameModeLine(;
void UI_DrawSessionAndGameModes(LocalClientNum_t localClientNum, const UIContextIndex_t contextIndex);
void UI_DrawGameModeHistory_DrawMode_HostedOrPlayed(;
void UI_DrawGameModeHistory_DrawMode(;
void UI_DrawGameModeHistory(const LocalClientNum_t localClientNum);
void UI_Refresh(LocalClientNum_t localClientNum);
char *UI_ReplaceConversionString(const char *sourceString, const char *replaceString);
char *UI_ReplaceConversionInt(const char *sourceString, int replaceInt);
const char *GetPLevelLockDescription(const LocalClientNum_t localClientNum, const int playlistId);
const char *UI_GetPlaylistDescription(;
void UI_SecondsAsTimeDisplay(int seconds, char *output, int maxChars);

//t6/code/src_noserver/ui/ui_mem_track.cpp
void UI_track_init();

//t6/code/src_noserver/ui/ui_motd.cpp
char MOTD_ParseVersion();
char MOTD_ParseMOTDVersion();
char MOTD_ParseSingleView();
char MOTD_ParseExpiration();
char MOTD_ParseImageCategory();
char MOTD_ParseTitle();
char MOTD_ParseMessage();
char MOTD_ParseImage();
char MOTD_ParseAction();
char MOTD_ParseActionContext();
char MOTD_ParseActionString();
char MOTD_ParseBannerTitle();
char MOTD_ParseBannerMessage();
char MOTD_ParseBannerImage();
char MOTD_ParseBannerAction();
char MOTD_ParseBannerActionContext();
char MOTD_ParseBannerActionString();
char MOTD_ParseEliteImage();
char MOTD_ParseFounderImage();

//t6/code/src_noserver/ui/ui_playlists.cpp
const char *Playlist_GetPlaylistFilename();
char *Playlist_Strdup(const char *src);
const char *Playlist_Strdup_Newline(const char *src);
char *Playlist_BeginRules();
bool Playlist_AppendRules(const char *base, const char *token);
const char *Playlist_GetLanguage();
int Playlist_GetCategoryIdByName(const char *name);
int Playlist_GetSuperCategoryIdByName(const char *name);
int ParseIntRange(const char *field, const char **pData, int min, int max);
char Playlist_ParseRequiredDLC(const char **pData, const char *name, const char **string);
void Playlist_SetPlaylistEntry(;
int Playlist_GetNumEntries(int playlistId);
playlistEntry *Playlist_GetEntry(int playlistId, int entry);
int Playlist_GetLeagueID(int playlistId);
BOOL Playlist_IsLeaguePlaylist(int playlistId);
int Playlist_GetParkingPlaylistForRealPlaylist(int realPlaylist);
const char *Playlist_GetPlaylistDescription(const ControllerIndex_t controllerIndex, const int playlistId);
int Playlist_IsLocked(const ControllerIndex_t controllerIndex, const int playlistId);
int Playlist_CategoryIsLocked(const ControllerIndex_t controllerIndex, const int categoryId);
int Playlist_GetMapPacksUsedByPlaylist(const int playlistId);
char Playlist_CanWeHostThisPlaylist(const ControllerIndex_t controllerIndex);
void Playlist_ResetWeights(const int playlistId, const PartyData_s *party);
void Playlist_ResetWeights(const int playlistId);
int Playlist_CalcTotalWeights(const int playlistId, const int lastSelection, const int lastToLastSelection);
int Playlist_FindEntryByWeight(;
playlistGametype *Playlist_FindGametype(const char *gametypeInternalName);
playlistMapList *Playlist_FindMaplist(const char *name);
int Playlist_GetGametypeCount();
const char *Playlist_GetGametypeLocalizedName(int index);
const char *Playlist_GetGametypeInternalName(int index);
int Playlist_GetVersionNumber();
int Playlist_GetUnlockXp(const ControllerIndex_t localControllerIndex, const int playlistId);
int Playlist_GetUnlockPLevel(const ControllerIndex_t localControllerIndex, const int playlistId);
int Playlist_GetMaxPartySize(const ControllerIndex_t localControllerIndex, const int playlistId);
int Playlist_GetMinPartySize(const ControllerIndex_t localControllerIndex, const int playlistId);
bool Playlist_IsGametypeBannable(const ControllerIndex_t localControllerIndex, const int playlistId);
int Playlist_GetCategoryId(int playlistId);
int Playlist_GetCurrentId();
void Playlist_SetCurrentId(int newId);
const dvar_t *Playlist_RegisterDvars();
;
void Playlist_ParsePlaylists(const char *buffer);
const char *Playlist_GetCategoryLocalizedName(const ControllerIndex_t controllerIndex, const int categoryId);
const char *Playlist_GetPlaylistName(const ControllerIndex_t controllerIndex, const int playlistId);
// int Playlist_ChooseEntry@<eax>(;
int Playlist_ChooseEntry(int a1, const PartyData_s *a2);
void Playlist_MigrateHost(;
const GfxViewParms *Playlist_GetMapName(const ControllerIndex_t localControllerIndex, const int entryNum);
const GfxViewParms *Playlist_GetScriptGameTypeName(;
char Playlist_RunRules(const ControllerIndex_t localControllerIndex, const int entryNum);
bool Playlist_DoesMapMatchPlaylistEntry(const int entryNum, const char *mapname);
bool Playlist_DoesGametypeMatchPlaylistEntry(const int entryNum, const char *gametype);
const char *Playlist_GetLocalizedGametypeName(const ControllerIndex_t localControllerIndex, const int entryNum);

//t6/code/src_noserver/ui/ui_shared.cpp
// void __thiscall MenuNameHash_t::MenuNameHash_t(MenuNameHash_t *this, const char *s);
int UI_GetUTFHeaderSize(const char *buff);
void Item_Fade(UIContextIndex_t contextIndex, itemDef_s *item, int fadeOut);
void Item_SetColor(itemDef_s *item, const char *name, UIContextIndex_t contextIndex, vec4_t *color);
void Menu_Setup(UiContext *dc);
int Color_Parse(const char **p, vec4_t *c);
int String_Parse(const char **p, char *out, int len);
BOOL Command_Parse(const char **p, char *out, int len);
void Window_Paint(;
bool Item_IsModal(itemDef_s *item);
int Rect_ContainsPoint(UIContextIndex_t contextIndex, const rectDef_s *rect, float x, float y);
int Menu_ItemsMatchingGroup(menuDef_t *menu, const char *name);
itemDef_s *Menu_GetMatchingItemByNumber(menuDef_t *menu, int index, const char *name);
void Script_SetColor(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_SetBackground(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
itemDef_s *Menu_FindItemByName(menuDef_t *menu, const char *p);
itemDef_s *Menu_FindFirstFocusableItemByName(;
animParamsDef_t *Item_FindStateByName(itemDef_s *item, const char *p);
void Item_LerpAnimationParameters(;
void UI_SetShaderTime(LocalClientNum_t localClientNum);
void Script_SetItemColor(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Menu_ShowItemByName(;
void Menu_FadeItemByName(;
int Menus_RemoveFromStack(const LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *pMenu);
void Menus_AddToStack(const LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *pMenu);
int Menus_MenuIsInStack(UiContext *dc, menuDef_t *menu);
LocalClientNum_t Menus_MenuInStackLocalClientNum(UiContext *dc, menuDef_t *menu);
int Menus_FindIndexByHash(UiContext *dc, unsigned int hash);
menuDef_t *Menus_FindByHash(UiContext *dc, unsigned int hash);
menuDef_t *Menus_FindByName(const UiContext *dc, const char *p);
void Menus_HideByName(const UiContext *dc, const char *menuName);
void Menus_ShowByName(const UiContext *dc, const char *windowName);
void Menus_RemoveMenu(XAssetHeader header);
char Item_DoesEventExist(itemDef_s *item, const char *eventName);
char Menus_DoesEventExist(menuDef_t *menu, const char *eventName);
void UI_ClearErrors();
void Script_Show(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_Hide(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_FadeIn(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_FadeOut(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_ShowMenu(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_HideMenu(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_OpParse(int *operand, const char **args);
int Script_IntParse(UiContext *dc, const char **args);
const char *Script_TableLookupParse(UiContext *dc, const char **args);
void Script_SetDvarStringUsingTable(;
void Script_SetDvar(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_ResetDvar(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_AddTextWrapper(;
void Script_Exec(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_ExecNow(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_ConditionalExecHandler(;
void Script_ConditionalResponseHandler(;
BOOL Script_ExecIfStringsEqual(const char *dvarValue, const char *testValue);
bool Script_ExecIfIntsEqual(const char *dvarValue, const char *testValue);
BOOL Script_ExecIfFloatsEqual(const char *dvarValue, const char *testValue);
void Script_ExecOnDvarStringValue(;
void Script_ExecOnDvarIntValue(;
void Script_ExecOnDvarFloatValue(;
void Script_ExecNowOnDvarStringValue(;
void Script_ExecNowOnDvarIntValue(;
void Script_ExecNowOnDvarFloatValue(;
void Script_RespondOnDvarStringValue(;
void Script_RespondOnDvarIntValue(;
void Script_RespondOnDvarFloatValue(;
void Script_SetLocalVarBool(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_SetLocalVarInt(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_SetLocalVarFloat(;
void Script_SetLocalVarString(;
void Script_FeederTop(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
void Script_SessionMode_SetOnlineGame(;
void Script_SessionMode_SetSystemLink(;
void Script_SessionMode_SetPrivate(;
void Script_GameMode_SetMode(;
;
;
void Script_ScriptMenuResponse(;
char Item_ArePrereqsSatisfied(GenericEventScript *eventScript, nestingStack_t *stack);
bool Item_IsConditionSatisfied(;
void Item_RunScript(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char *s);
void UI_SetLocalVarBool_f();
void UI_SetLocalVarInt_f();
void UI_SetLocalVarFloat_f();
void UI_SetLocalVarString_f();
void UI_FadeItem_f();
void UI_ShowItem_f();
void UI_HideItem_f();
void UI_ShowMenu_f();
void UI_HideMenu_f();
void UI_ChangeMenuOpenSlideDirection_f();
void UI_ChangeMenuCloseSlideDirection_f();
void UI_OpenToastPopup_f();
void UI_AddToFeeder_f();
void UI_AddToFeederExtended_f();
void UI_ClearFeeder_f();
void UI_ClearFeederWithoutResetCursor_f();
void UI_RaiseFeederEvent_f();
void UI_RefreshFeeder_f();
void UI_ChangeRowStatus_f();
void UI_ValidatePrivateMatchGametype_f();
void UI_SetActiveMenu_f();
void UI_KickPlayer_f();
float Item_ListBox_GetMaxHeight(;
// int Item_ListBox_Viewmax@<eax>(;
float Item_Slider_ThumbPosition(const LocalClientNum_t localClientNum, itemDef_s *item);
int Item_Slider_OverSlider(;
int Item_ListBox_GetIndexForMouse(UIContextIndex_t contextIndex, itemDef_s *item, float x, float y);
void Item_Listbox_Mouse_Column_Set(;
void Item_MouseLeave(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
bool Item_ShouldHandleKey(UiContext *dc, itemDef_s *item, int key);
bool Item_YesNo_IsActionKey(int key);
int Item_YesNo_HandleKey(UiContext *dc, itemDef_s *item, int key);
int Item_DvarEnum_CountSettings(itemDef_s *item);
int Item_Multi_FindDvarByValue(itemDef_s *item);
int Item_ProfileMulti_FindVarByValue(LocalClientNum_t localClientNum, itemDef_s *item);
const char *Item_Multi_Setting(itemDef_s *item);
const char *Item_ProfileMulti_Setting(LocalClientNum_t localClientNum, itemDef_s *item);
int Item_DvarEnum_EnumIndex(itemDef_s *item);
const char *Item_DvarEnum_Setting(LocalClientNum_t localClientNum, itemDef_s *item);
int Item_List_NextEntryForKey(int key, int current, int count);
int Item_Multi_HandleKey(UiContext *dc, itemDef_s *item, int key);
int Item_ProfileMulti_HandleKey(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, int key);
int Item_DvarEnum_HandleKey(UiContext *dc, itemDef_s *item, int key);
bool Item_IsTextField(const itemDef_s *item);
void Item_TextField_BeginEdit(;
void Item_TextField_EnsureCursorVisible(UIContextIndex_t contextIndex, itemDef_s *item, const char *text);
void Scroll_Slider_SetThumbPos(UiContext *dc, itemDef_s *item);
void Scroll_Slider_ThumbFunc(;
int Item_Slider_HandleKey(;
void Menus_PrintAllLoadedMenus(UiContext *dc);
int Display_VisibleMenuCount(UiContext *dc);
rectDef_s *Item_CorrectedTextRect(UIContextIndex_t contextIndex, itemDef_s *item);
bool Menu_ItemsAreAnimating(LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *menu);
Font_s *Item_GetFont(UIContextIndex_t contextIndex, const itemDef_s *item);
void Item_SetTextExtents(;
void Item_TextColor(UiContext *dc, itemDef_s *item, vec4_t *newColor);
int UI_PickWordWrapLineWidth(;
void DrawWrappedText(;
void DrawWrappedTextScissored(;
void UI_DrawWrappedText(;
void UI_DrawWrappedTextScissored(;
void Item_Text_AutoWrapped_Paint(;
void GetPlatformCommand(LocalClientNum_t localClientNum, const char *command, const char **consoleCommand);
// int UI_GetKeyBindingLocalizedString@<eax>(;
void Item_Slider_Paint(const LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
int Display_KeyBindPending();
bool Item_Bind_IsActionKey(UiContext *dc, itemDef_s *item, int key);
int Item_Bind_HandleKey(;
float Item_GetTextAlignAdj(const int alignment, float width, float textWidth);
void Item_ListBox_PaintTextElem(;
void Item_ListBox_PaintBackground(;
void Item_ListBox_PaintHighlight(const UIContextIndex_t contextIndex, itemDef_s *item, float x, float y);
void Item_ListBox_PaintItemIndicators(;
void Item_GameMsgWindow_Paint(const LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
menuDef_t *Menu_GetFocused(UiContext *dc);
int Menus_AnyFullScreenVisible(UiContext *dc);
// char Menu_IsVisible@<al>(;
void UI_SetupTextShaderParams(Font_s *font, textDef_s *textDefPtr);
void UI_SetSystemCursorPos(UiContext *dc, float x, float y);
int Menu_OverActiveItem(UIContextIndex_t contextIndex, menuDef_t *menu, float x, float y);
void TRACK_ui_shared();
void UI_ClearLocalUIVisibilityBits(LocalClientNum_t localClientNum);
void UI_SetLocalUIVisbilityBit(LocalClientNum_t localClientNum, int bitShift, int value);
bool Menus_ActiveMenuAllowSignin(UiContext *dc);
char Menu_DoesMenuOrParentsHaveControlFlag(UiContext *dc, menuDef_t *menu, int controlFlag);
int Menu_GetSpecifiedControlFlagFromStack(UiContext *dc, menuDef_t *menu);
void Phys_ReEvalPriority();
void Script_SetUIVisibilityBit(;
void Item_RunSingleEventScript(;
void Item_RunEventScript(;
void UIAnimation_RunEventScript(;
void UI_RefreshFeederSelection_f();
void UI_PlaySound_f();
int Item_ListBox_MaxScroll(;
float Item_ListBox_ThumbPosition(;
float Item_ListBox_ThumbDrawPosition(const LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
int Item_ListBox_OverLB(;
void Item_ListBox_SetCursorPos(;
void Item_ListBox_Page(;
void Item_ListBox_Scroll(;
void Item_Action(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
int Menu_CheckOnKey(UiContext *dc, menuDef_t *menu);
void Item_Text_Paint(const LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
void Item_TextField_Paint(const LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
void Item_YesNo_Paint(const LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
char UI_GetSticksTranslatedString(LocalClientNum_t localClientNum, const char *command, char *keys);
void Item_Bind_Paint(const LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
// void Item_ListBox_Paint(float a1@<esi>, LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
void Item_OwnerDraw_Paint(const LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
void Menu_RunFocusScript(UiContext *dc, menuDef_t *menu);
void Menu_RunLeaveFocusScript(UiContext *dc, menuDef_t *menu);
itemDef_s *Menu_ClearFocus(LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *menu);
void Item_UpdateAnimation(;
void Item_AnimateToState(;
void UI_AnimateItemInternal(;
void UI_AnimateItem(;
void UI_AnimateItemSysTime(;
void Menu_LoseFocusDueToOpen(const LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *menu);
void Menu_CallOnFocusDueToOpen(const LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *menu);
void Menu_GainFocusDueToClose(const LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *menu);
void Menu_RunCloseScript(UiContext *dc, menuDef_t *menu);
void Menus_CompleteItemAnimations(const LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *menu);
void Menus_Close(const LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *menu);
void Menus_CloseByName(const LocalClientNum_t localClientNum, UiContext *dc, const char *p);
void Menus_CloseAll(const LocalClientNum_t localClientNum, UiContext *dc);
void Menus_CloseAllBehindMain(const LocalClientNum_t localClientNum, UiContext *dc);
void Menus_CloseFromMenuToTopOfStack(;
bool RemoveMenuFromBlurStack(const LocalClientNum_t localClientNum, UiContext *dc, const char *menuName);
void Script_ActivateBlur(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
void Script_DeactivateBlur(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
int GetBlurFocus(const LocalClientNum_t localClientNum, UiContext *dc);
void Script_Close(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_CloseImmediate(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_InGameClose(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_ChangeState(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_ExecKeyHandler(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_FeederBottom(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
void UI_CloseMenu_f();
void UI_CloseMenuImmediate_f();
void UI_MoveFeeder_f();
int Item_SetFocus(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, float x, float y);
void Item_ListBox_ModalSelection(;
void Item_ListBox_MouseEnter(;
void Item_MouseEnter(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, float x, float y);
int Item_ListBox_HandleKey(;
void Scroll_ListBox_AutoFunc(const LocalClientNum_t localClientNum, UiContext *dc, void *p);
void Scroll_ListBox_ThumbFunc(const LocalClientNum_t localClientNum, UiContext *dc, void *p);
void Item_StartCapture(const LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, int key);
int Item_HandleKey(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, int key, int down);
itemDef_s *Menu_SetPrevCursorItem(LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *menu);
itemDef_s *Menu_SetNextCursorItem(;
// int Menu_HandleMouseMove@<eax>(;
void Menu_PerformTransitionEffects(;
// int Display_MouseMove@<eax>(menuDef_t *a1@<edi>, LocalClientNum_t localClientNum, UiContext *dc);
void UI_AddMenuList(const LocalClientNum_t localClientNum, UiContext *dc, MenuList *menuList, int close);
void Menus_SetFocusToItem(;
itemDef_s *Menu_FocusFirstSelectableItem(LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *menu);
void Script_FocusFirstInMenu(;
void Script_SetFocus(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_SetFocusByDvar(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void UI_FocusItem_f();
int Item_TextField_HandleKey(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, int key);
void Menus_SetupOpenMenu(LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *menu);
void Menus_HandleOOBClick(;
void Menu_HandleKey(;
void Item_Paint(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item);
// char Menu_Paint@<al>(;
void Script_ExecKeyPress(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Menus_Open(LocalClientNum_t localClientNum, UiContext *dc, menuDef_t *menu);
int Menus_OpenByName(LocalClientNum_t localClientNum, UiContext *dc, const char *p);
int Menus_OpenImmediateByName(LocalClientNum_t localClientNum, UiContext *dc, const char *p);
void Script_Open(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_OpenImmediate(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void Script_InGameOpen(LocalClientNum_t localClientNum, UiContext *dc, itemDef_s *item, const char **args);
void UI_OpenMenu_f();
void UI_OpenMenuImmediate_f();
void UI_RegisterCmds();
void Menu_PaintAll_AppendToVisibleList(char *stringBegin, unsigned int stringSize, const char *stringToAppend);
void Menu_PaintAll(LocalClientNum_t localClientNum, UiContext *dc);

//#include "ui/ui_shared_load_db.h"

//t6/code/src_noserver/ui/ui_shared_obj.cpp
void TRACK_ui_shared_obj();
void Menu_FreeItemMemory(itemDef_s *item);
void Menu_FreeMemory(menuDef_t *menu);
void Menus_FreeAllMemory(UiContext *dc);
void UI_MapLoadInfo(const char *filename);
void PC_SourceError(int handle, char *format, ...);
int PC_Float_Expression_Parse(int handle, float *f);
int PC_Int_ParseLine(int handle, int *i);
int PC_Flag_ParseOptional(int handle, int *i);
int PC_Int_Expression_Parse(int handle, int *i);
int PC_String_Parse(int handle, const char **out);
int PC_Script_Parse(int handle, const char **out);
int PC_CndStackPush(;
int PC_CndStackPopLevel();
int PC_CndStackAddConditionsToScript(GenericEventScript **baseScript, char *accumulatedScriptCommands);
int PC_EventScript_Parse(int handle, GenericEventScript **baseScript);
void Menu_Init(menuDef_t *menu, int imageTrack);
void Item_Init(itemDef_s *item, int imageTrack);
void Item_PostParse(itemDef_s *item);
int MenuParse_name(menuDef_t *menu, int handle);
int MenuParse_visible(menuDef_t *menu, int handle);
int MenuParse_visiblityBits(menuDef_t *menu, int handle);
int MenuParse_onFocus(menuDef_t *menu);
int MenuParse_leaveFocus(menuDef_t *menu);
int MenuParse_onOpen(menuDef_t *menu);
int MenuParse_onClose(menuDef_t *menu);
int MenuParse_onESC(menuDef_t *menu);
BOOL MenuParse_execExp(menuDef_t *menu, int handle);
int MenuParse_background(menuDef_t *menu, int handle);
int MenuParse_popup(menuDef_t *menu);
int MenuParse_outOfBounds(menuDef_t *menu);
int MenuParse_soundLoop(menuDef_t *menu, int handle);
void Item_ValidateTypeData(itemDef_s *item, int handle);
int MenuParse_execKey(menuDef_t *menu, int handle);
int MenuParse_legacySplitScreenScale(menuDef_t *menu);
int MenuParse_hiddenDuringScope(menuDef_t *menu);
int MenuParse_hiddenDuringFlashbang(menuDef_t *menu);
int MenuParse_hiddenDuringUI(menuDef_t *menu);
int MenuParse_allowedBinding(menuDef_t *menu, int handle);
int MenuParse_allowSignIn(menuDef_t *menu);
const char *UI_FileText(const char *fileName);
int ItemParse_name(itemDef_s *item, int handle);
int ItemParse_focusSound(itemDef_s *item);
int ItemParse_text(itemDef_s *item, int handle);
int ItemParse_textfile(itemDef_s *item, int handle);
int ItemParse_textsavegame(itemDef_s *item);
int ItemParse_textcinematicsubtitle(itemDef_s *item);
int ItemParse_group(itemDef_s *item, int handle);
int ItemParse_decoration(itemDef_s *item);
// int ItemParse_notselectable@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item);
// int ItemParse_noScrollBars@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item);
// int ItemParse_noBlinkingHighlight@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item);
// int ItemParse_usePaging@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item);
int ItemParse_autowrapped(itemDef_s *item);
int ItemParse_horizontalscroll(itemDef_s *item);
int ItemParse_visible(itemDef_s *item, int handle);
int ItemParse_visiblityBits(itemDef_s *item, int handle);
int ItemParse_modal(itemDef_s *item);
int ItemParse_background(itemDef_s *item, int handle);
// int ItemParse_doubleClick@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item);
// int ItemParse_rightClick@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item);
int ItemParse_onEnter(itemDef_s *item);
int ItemParse_onFocus(itemDef_s *item);
int ItemParse_leaveFocus(itemDef_s *item);
BOOL ItemParse_mouseEnter(itemDef_s *item);
BOOL ItemParse_mouseExit(itemDef_s *item);
BOOL ItemParse_mouseEnterText(itemDef_s *item);
BOOL ItemParse_mouseExitText(itemDef_s *item);
int ItemParse_action(itemDef_s *item);
int ItemParse_accept(itemDef_s *item);
int ItemParse_dvarTest(itemDef_s *item, int handle);
// int ItemParse_dvar@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_profile@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int Item_Parse_maxCharsGotoNext@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item);
// int ItemParse_dvarStrList@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_profileStrList@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_dvarEnumList@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_actionOnEnterPressOnly@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item);
// int ItemParse_enableDvar@<eax>(const char **a1@<edx>, int a2@<ecx>, itemDef_s *item);
// int ItemParse_disableDvar@<eax>(const char **a1@<edx>, int a2@<ecx>, itemDef_s *item);
// int ItemParse_showDvar@<eax>(const char **a1@<edx>, int a2@<ecx>, itemDef_s *item);
// int ItemParse_hideDvar@<eax>(const char **a1@<edx>, int a2@<ecx>, itemDef_s *item);
// int ItemParse_focusDvar@<eax>(const char **a1@<edx>, int a2@<ecx>, itemDef_s *item);
BOOL ItemParse_onEvent(itemDef_s *item, int handle);
int ItemParse_execKey(itemDef_s *item, int handle);
BOOL ItemParse_execExp(itemDef_s *item, int handle);
// int ItemParse_selectIcon@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_backgroundItemListbox@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_highlightTexture@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// listBoxDef_s *ItemParse_onListboxSelectionChange@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item);
void Menu_PostParse(menuDef_t *menu);
MenuList *UI_LoadMenus_FastFile(const char *menuFile);
int PC_Float_Parse(int handle, float *f);
int PC_Color_Parse(int handle, vec4_t *c);
int PC_Int_Parse(int handle, int *i);
// int PC_Rect_Parse@<eax>(float *a1@<edx>, int handle, rectDef_s *r);
int WindowParse_frame(windowDef_t *window, int handle);
// int MenuParse_fullscreen@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_rect@<eax>(float *a1@<edx>, menuDef_t *menu, int handle);
// int ItemParse_style@<eax>(int *a1@<edx>, itemDef_s *item, int handle);
// int ItemParse_border@<eax>(int *a1@<edx>, itemDef_s *item, int handle);
// int MenuParse_borderSize@<eax>(float *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_backcolor@<eax>(vec4_t *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_forecolor@<eax>(vec4_t *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_bordercolor@<eax>(vec4_t *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_focuscolor@<eax>(vec4_t *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_disablecolor@<eax>(vec4_t *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_outlinecolor@<eax>(vec4_t *a1@<edx>, menuDef_t *menu, int handle);
// int ItemParse_ownerdrawFlag@<eax>(int *a1@<edx>, itemDef_s *item, int handle);
// int MenuParse_ownerdraw@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_fadeClamp@<eax>(float *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_fadeAmount@<eax>(float *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_fadeInAmount@<eax>(float *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_fadeCycle@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_execKeyInt@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_blurWorld@<eax>(float *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_ui3dWindowId@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_priority@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_openSlideSpeed@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_closeSlideSpeed@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_openSlideDirection@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_closeSlideDirection@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_openFadingTime@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_closeFadingTime@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int MenuParse_control@<eax>(int *a1@<edx>, menuDef_t *menu, int handle);
// int ItemParse_rect@<eax>(float *a1@<edx>, itemDef_s *item, int handle);
// int ItemParse_origin@<eax>(int *a1@<edx>, itemDef_s *item, int handle);
// int ItemParse_type@<eax>(int *a1@<edx>, itemDef_s *item, int handle);
// listBoxDef_s *ItemParse_elementwidth@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// listBoxDef_s *ItemParse_elementheight@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
BOOL ItemParse_special(itemDef_s *item, int handle);
// int ItemParse_elementtype@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_columns@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
int ItemParse_menuColDef(listBoxDef_s *listPtr, int handle, MenuCell *cells, int cellCount);
// int ItemParse_menuItemsDef@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_menuarea@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_userarea@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// BOOL ItemParse_bordersize@<eax>(float *a1@<edx>, itemDef_s *item, int handle);
BOOL ItemParse_ownerdraw(itemDef_s *item, int handle);
BOOL ItemParse_align(itemDef_s *item, int handle);
int ItemParse_textalign(itemDef_s *item, int handle);
BOOL ItemParse_textalignx(itemDef_s *item, int handle);
BOOL ItemParse_textaligny(itemDef_s *item, int handle);
BOOL ItemParse_textscale(itemDef_s *item, int handle);
BOOL ItemParse_textpadding(itemDef_s *item, int handle);
int ItemParse_fontColor(itemDef_s *item, int handle);
int ItemParse_glowColor(itemDef_s *item, int handle);
int ItemParse_shadowColor(itemDef_s *item, int handle);
BOOL ItemParse_fontBlur(itemDef_s *item, int handle);
BOOL ItemParse_glowSize(itemDef_s *item, int handle);
BOOL ItemParse_shadowSize(itemDef_s *item, int handle);
int ItemParse_shadowOffset(itemDef_s *item, int handle);
BOOL ItemParse_textstyle(itemDef_s *item, int handle);
// BOOL ItemParse_rotation@<eax>(float *a1@<edx>, itemDef_s *item, int handle);
BOOL ItemParse_textfont(itemDef_s *item, int handle);
int ItemParse_backcolor(itemDef_s *item, int handle);
// int ItemParse_forecolor@<eax>(float *a1@<edx>, itemDef_s *item, int handle);
int ItemParse_bordercolor(itemDef_s *item, int handle);
int ItemParse_frame(windowDef_t *a1, int a2);
// BOOL ItemParse_outlinecolor@<eax>(vec4_t *a1@<edx>, itemDef_s *item, int handle);
// int ItemParse_profileFloat@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_maxChars@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_maxPaintChars@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_dvarFloat@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_dvarFloatList@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_profileFloatList@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_execKeyInt@<eax>(int *a1@<edx>, itemDef_s *item, int handle);
// int ItemParse_gameMsgWindowIndex@<eax>(int *a1@<edx>, itemDef_s *item, int handle);
// int ItemParse_gameMsgWindowMode@<eax>(int *a1@<edx>, itemDef_s *item, int handle);
// listBoxDef_s *ItemParse_selectBorder@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// listBoxDef_s *ItemParse_elementHighlightColor@<eax>(;
// listBoxDef_s *ItemParse_elementBackgroundColor@<eax>(;
// listBoxDef_s *ItemParse_disableColor@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// listBoxDef_s *ItemParse_focusColor@<eax>(int a1@<edx>, itemDef_s *a2@<ecx>, itemDef_s *item, int handle);
// int ItemParse_ui3dWindowId@<eax>(int *a1@<edx>, itemDef_s *item, int handle);
int Asset_Parse(int handle, int imageTrack);
int Item_Parse(int handle, itemDef_s *item);
int MenuParse_itemDef(menuDef_t *menu, int handle);
void Menu_SetupKeywordHash();
int ItemParse_state(itemDef_s *item, int handle);
void Item_SetupKeywordHash();
int Menu_Parse(int handle, menuDef_t *menu);
bool Menu_New(int handle, int imageTrack);
bool UI_ParseMenuInternal(const char *menuFile, int imageTrack);
MenuList *UI_LoadMenu_LoadObj(const char *menuFile);
MenuList *UI_LoadMenu();
int Load_Menu(const char **p, int imageTrack);
MenuList *UI_LoadMenus_LoadObj(const char *menuFile);
MenuList *UI_LoadMenus();

//#include "ui/ui_ui3d_util.h"

//t6/code/src_noserver/ui/ui_utils.cpp
void TRACK_ui_utils();
void Window_SetDynamicFlags(UIContextIndex_t contextIndex, windowDef_t *w, const int flags);
void Window_AddDynamicFlags(UIContextIndex_t contextIndex, windowDef_t *w, const int newFlags);
void Window_RemoveDynamicFlags(UIContextIndex_t contextIndex, windowDef_t *w, const int newFlags);
void Window_SetStaticFlags(windowDef_t *w, const int flags);
void Menu_SetCursorItem(UIContextIndex_t contextIndex, menuDef_t *menu, int cursorItem);
BOOL Item_EnableShowViaDvar(const itemDef_s *item, int flag);
void Item_SetTextRect(UIContextIndex_t contextIndex, itemDef_s *item, const rectDef_s *textRect);
int Item_IsEditFieldDef(itemDef_s *item);
int Item_IsTextDefType(itemDef_s *item);
int Item_IsFocusDefType(itemDef_s *item);
BOOL Item_IsOwnerDrawDefType(itemDef_s *item);
editFieldDef_s *Item_GetEditFieldDef(itemDef_s *item);
multiDef_s *Item_GetMultiDef(itemDef_s *item);
profileMultiDef_s *Item_GetProfileMultiDef(itemDef_s *item);
ownerDrawDef_s *Item_GetOwnerDrawDef(itemDef_s *item);
textDef_s *Item_GetTextDef(itemDef_s *item);
focusItemDef_s *Item_GetFocusItemDef(itemDef_s *item);
listBoxDef_s *Item_GetListBoxDef(itemDef_s *item);
double Item_GetListBoxFeederID(const itemDef_s *item);
enumDvarDef_s *Item_GetEnumDvarName(itemDef_s *item);
gameMsgDef_s *Item_GetGameMsgDef(itemDef_s *item);
void Item_PropertiesToAnimState(itemDef_s *item, animParamsDef_t *animParams);
void Item_AnimStateToProperties(animParamsDef_t *animParams, itemDef_s *item);
int hashForString(const char *str);
void *UI_Alloc(int size, int alignment);
void String_Init();
char *String_Alloc(const char *p);
int Float_Parse(const char **p, float *f);
void UI_GetGameTypesList_LoadObj();
void UI_GetGameTypesList_FastFile();
void UI_GetGameTypesList();
char *UI_GetBusyDotsIndicator();
void UI_ListMenus_f();
void __thiscall CL_SelectStringTableEntryInDvar_f(const StringTable *this);
bool UI_VerifyString(const char *str);
int Item_IsVisible(const LocalClientNum_t localClientNum, UIContextIndex_t contextIndex, itemDef_s *item);
int Item_GetCursorPosOffset(UIContextIndex_t contextIndex, itemDef_s *item, const char *text, int delta);
BOOL ListBox_HasValidCursorPos(UIContextIndex_t contextIndex, itemDef_s *item);
void Item_SetScreenCoords(;
void Menu_UpdatePosition(UIContextIndex_t contextIndex, menuDef_t *menu);

//#include "ui/ui_utils.h"

//#include "ui/ui_utils_api.h"

//t6/code/src_noserver/ui/ui_voting.cpp
bool Voting_SetBoolAttribute(bool *attribute, const char *string);
bool Voting_SetIntAttribute(int *attribute, const char *string);
bool Voting_SetStringAttribute(char *attribute, const char *string, int attributeSize);
bool Voting_SetStringRefAttribute(char *attribute, const char *string, int attributeSize);
char Voting_ParseVersion();
bool Voting_ParseVotingVersion(int *a1, const char *a2);
bool Voting_ParseExpiration(int *a1, const char *a2);
bool Voting_ParseVotingInterval(int *a1, const char *a2);
bool Voting_ParseImageCategory(int *a1, const char *a2);
bool Voting_ParseViewCount(int *a1, const char *a2);
bool Voting_ParseTitle(char *a1, const char *a2);
bool Voting_ParseSubtitle(char *a1, const char *a2);
bool Voting_ParseVoteForString(char *a1, const char *a2);
bool Voting_ParseVotingItem_ImageName(int a1, const char *a2);
bool Voting_ParseVotingItem_IsLocalImage(int a1, const char *a2);
bool Voting_ParseVotingItem_CounterName(int a1, const char *a2);
bool Voting_ParseVotingItem_SelectStringRef(int a1, const char *a2);
bool Voting_ParseVotingItem_Position(int a1, const char *a2);
char Voting_ParseKeys(int keyCount, votingHandler_t *keyHandlers, int numKeyHandlers);
char Voting_ParseVoteItemsArray();

