#pragma once

#include "types.h"

//t6/code/src_noserver/live/live.cpp
const char *Live_GetDWEnviroment();
void Live_Base_LobbyPump(const ControllerIndex_t localControllerIndex);
void Live_Base_ContentStreamingInit(ControllerIndex_t localControllerIndex);
void Live_Base_PooledStorageInit(ControllerIndex_t localControllerIndex);
ControllerIndex_t Live_GetControllerFromXuid(unsigned __int64 xuid);
bool Live_IsUserSignedInToDemonware(const ControllerIndex_t controllerIndex);
void __cdecl Live_ComErrorIfBuildExpired();
void Live_LeaveAllPartiesCmd();
void __cdecl Sound_Frame();
void Live_CloseAllBusyPopups_f();
void Live_DelayedComError(const char *comErrorString);
void Live_SetComErrorIfJoinInProgressFails(bool shouldComError);
void Live_ResetLobbyModeDvars(PartyData_s *party, const eGameModes currentLobbyMode, const dvar_t *playerCountDvar, const dvar_t *localPlayerCountDvar);
unsigned int Live_IsUserInGame(const ControllerIndex_t controllerIndex);
int Live_IsAnyUserInGame();
bool Live_IsGeoLocationDataRetrieved();
bdDMLHierarchicalInfo *Live_GetGeoLocation();
bool Live_GetUserGeoLocationDataSuccess(TaskRecord *task);
char Live_GetUserGeoLocationDataFailure(TaskRecord *task);
bool Live_NATTypeAllowed(XONLINE_NAT_TYPE NATtype);
bool Live_CanHostServer(const ControllerIndex_t localControllerIndex, const int playerCount);
void Live_AwardAchievement_f();
int Live_SessionMode_EncodePlaylistNumber(int playlistNum);
int Live_SessionMode_DecodePlaylistNumber(int playlistNum);
unsigned __int64 Live_GetLocalXUID(const ControllerIndex_t controllerIndex, unsigned __int64 myXUID);
void Live_Init();
bool Live_GetConnectivityInformation(ControllerIndex_t controllerIndex, int *infoBitmask, bool outputDebugInfo);
void Live_GetGeoLocationData(const ControllerIndex_t controllerIndex);
bool Live_CanHostServer(const ControllerIndex_t localControllerIndex, const int playerCount, int *failureReason);

//t6/code/src_noserver/live/live_anticheat.cpp
void LiveAntiCheat_BanDoConnected();
void LiveAntiCheat_DWPlayerBanned(unsigned __int64 userID, unsigned int reputationLevel);
void LiveAntiCheat_GenerateCRC32Checksum(const unsigned __int8 *data, int length, unsigned int *key);
unsigned int LiveAntiCheat_GenerateCRC32ChecksumSplit(const unsigned __int8 *data, int length, unsigned __int64 key);
HashInfo *LiveAntiCheat_StartHash(challengeTest_t type, unsigned int start, unsigned int length, unsigned int blockSize, unsigned __int64 key);
bool LiveAntiCheat_ContinueHash(void *handle);
char LiveAntiCheat_CompleteHash(void *handle, unsigned __int64 *result);
void LiveAntiCheat_AnswerChallengesRetry(const ControllerIndex_t controllerIndex);
char LiveAntiCheat_AnswerChallengesFailure(TaskRecord *task);
void LiveAntiCheat_ResetChallengeResponse(const ControllerIndex_t controllerIndex);
void LiveAntiCheat_ClearGameReport();
void LiveAntiCheat_SetThresholdExceeded(int threshold);
void LiveAntiCheat_ReportLaggedDamage();
void LiveAntiCheat_SetGameReportTags(int *numTags, bdTag *tags);
TaskRecord *LiveAntiCheat_AnswerChallenges(const ControllerIndex_t controllerIndex);
char LiveAntiCheat_AnswerChallengesSuccess(TaskRecord *task);
// void LiveAntiCheat_OnChallengesReceived(unsigned __int64 userID, bdReference<bdAntiCheatChallenges> challenges);
// bool LiveAntiCheat_AnswerChecksumRequest(const ControllerIndex_t controllerIndex, const bdArray<bdAntiCheatChallengeParam> *params, __int64 *checksum, challengeTest_t checksumType);
// bool LiveAntiCheat_AnswerDvarRequest(const ControllerIndex_t controllerIndex, const bdArray<bdAntiCheatChallengeParam> *params, __int64 *response);
// bool LiveAntiCheat_AnswerDvarFloatRequest(const ControllerIndex_t controllerIndex, const bdArray<bdAntiCheatChallengeParam> *params, __int64 *response);
// bool LiveAntiCheat_AnswerExpressionRequest(const ControllerIndex_t controllerIndex, const bdArray<bdAntiCheatChallengeParam> *params, __int64 *response);
// bool __cdecl LiveAntiCheat_GetChallengeResponse(const ControllerIndex_t controllerIndex, unsigned __int16 functionID, const bdArray<bdAntiCheatChallengeParam> *params, __int64 *response);
void LiveAntiCheat_ProcessChallenges(const ControllerIndex_t controllerIndex);

//t6/code/src_noserver/live/live_counter.cpp
char LiveCounter_UploadAllCountersComplete();
char LiveCounter_UploadAllCountersFailure(TaskRecord *task);
char LiveCounter_DownloadAllCountersComplete();
char LiveCounter_DownloadAllCountersFailure();
void LiveCounter_AddToQueueByID(int counterID, __int64 increment);
void LiveCounter_ForceFlushQueue_f();
void LiveCounter_Dump_f();
int LiveCounter_GetCounterTotalValue(int counterID);
int LiveCounter_CounterStringToID(const char *counterType);
void LiveCounter_SetupCounters();
void LiveCounter_AddToQueueByName(const char *counterType, __int64 increment);
void LiveCounter_AddToQueueByName_f();
void LiveCounter_Init();

//t6/code/src_noserver/live/live_dedicated.cpp
char *dwSelectLSGAddress();
char *dwSelectAuthAddress();
void Live_SetTitleIDFromCommandLine();
void Live_SetAuthAddrFromCommandLine();
void Live_SetLsgAddrFromCommandLine();
int Live_GetTitleID();
void SV_SwitchPlaylists(const int newplaylist);
void SV_PlaylistDvarChanged(const dvar_t *playlistdvar);
void Live_OnDWConnect(const ControllerIndex_t localControllerIndex);
void Live_OnDWDisconnect(const ControllerIndex_t localControllerIndex);
const char *Live_DedicatedReadDWKey();
bool Live_Base_AuthorizeLicenseWithDW(const ControllerIndex_t controllerIndex, dediUserData_t *userData);
bool Live_Base_HandleAuthServiceReady(const ControllerIndex_t controllerIndex, dediUserData_t *userData, bdAuthService *authService);
void Live_Base_StateAuthorizing(const ControllerIndex_t controllerIndex, dediUserData_t *userData);
void Live_Base_StateConnecting(const ControllerIndex_t controllerIndex, dediUserData_t *userData);
void Live_Base_StateError(const ControllerIndex_t controllerIndex, dediUserData_t *userData);
void Live_Base_Init();
char Live_Base_UserGetName(const ControllerIndex_t controllerIndex, char *buff, int buffSize);
char Live_Base_UserGetXuid(const ControllerIndex_t controllerIndex, unsigned __int64 *xuid);
ControllerIndex_t Live_Base_GetControllerFromXUID(const unsigned __int64 xuid);
bool Live_IsSignedInToLive(ControllerIndex_t controllerIndex);
unsigned __int64 Live_GetXuid(ControllerIndex_t controllerIndex);
void Live_SetAddressForDedicatedServer(MatchMakingInfo *sessionInfo);
const char *SV_GetLSPID();
int SV_GetLSPPort();
void Live_FakeDLC_ClientDisconnect();
void Live_FakeDLC_ClientJoin(unsigned int contentFlags);
unsigned int Live_FakeDLC_GetFlags();
void MatchmakingHopper_UpdateState(matchmakingHopperState_t newState);
void MatchmakingHopper_Init();
char MatchmakingHopper_ClientJoin(int memberPlaylist);
void MatchmakingHopper_Frame();
BOOL MatchmakingHopper_isParked();
void Live_SetPingTestKey();
void Live_Base_StateConnected(const ControllerIndex_t controllerIndex, dediUserData_t *userData);
void Live_Base_PumpForController(dediUserData_t *a1, ControllerIndex_t a2, const ControllerIndex_t controllerIndex);
void Live_Base_Pump(ControllerIndex_t a1, dediUserData_t *a2);
void Live_HandleDemonwareLSP(dediUserData_t *a1, ControllerIndex_t a2, ControllerIndex_t localControllerIndex);
// void Live_DedicatedFrame(int a1@<ebp>);

//t6/code/src_noserver/live/live_doublexp.cpp
int Live_DoubleXPGetGroupMaskFromString(const char *groupString);
void Live_DoubleXPSetServerGroupMasks();
unsigned int Live_DoubleXPGetServerGroupMask();
unsigned int Live_DoubleXPGetServerGunGroupMask();
unsigned int Live_DoubleXPGetGroupMask(doubleXPGroups_e group);
unsigned int Live_DoubleXPGetGroupMaskForController(const ControllerIndex_t controllerIndex);
void Live_DoubleXPRecordIW6Promo(const ControllerIndex_t controllerIndex, bool accessed);
void Live_DoubleXPUpdatGroupMaskForController(const ControllerIndex_t controllerIndex, bdKeyValuePair *values, int count);
void Live_DoubleXPUpdateMapPackInfo(bool ignoreMountedControllers);
void Live_DoubleXPUpdateMapPackInfoCmd();
void Live_DoubleXPRecordSeasonPass(const ControllerIndex_t controllerIndex);
void Live_DoubleXPSetGroupMaskForController(const ControllerIndex_t controllerIndex, bool includeKeyArchive);
int Live_DoubleXPGetContentMask(const char *contentPakNames);
void Live_DoubleXPInit();
void Live_DoubleXPUnsetGroupManuallyForController(const ControllerIndex_t controllerIndex, int groupIndex);

//t6/code/src_noserver/live/live_elite.cpp
void ClearRetrievedEliteAccountInfo();
TaskRecord *LiveElite_ClanLeave(const ControllerIndex_t localControllerIndex, unsigned __int64 teamid);
char LiveElite_ClanLeaveSuccess(TaskRecord *task);
char LiveElite_ClanLeaveFailure(TaskRecord *task);
char LiveElite_ClanInviteSuccess(TaskRecord *task);
char LiveElite_ClanInviteFailure(TaskRecord *task);
TaskRecord *LiveElite_CreateClan(const ControllerIndex_t localControllerIndex, const char *teamName);
char LiveElite_CreateClanSuccess(TaskRecord *task);
char LiveElite_CreateClanFailure(TaskRecord *task);
TaskRecord *LiveElite_TeamSetPublicProfile(const ControllerIndex_t localControllerIndex, __int64 teamId, const char *clantag);
char LiveElite_TeamSetPublicProfileSuccess(TaskRecord *task);
char LiveElite_TeamSetPublicProfileFailure(TaskRecord *task);
TaskRecord *LiveElite_TeamSetPrivateProfile(const ControllerIndex_t localControllerIndex, __int64 teamId, const char *motd);
char LiveElite_TeamSetPrivateProfileSuccess(TaskRecord *task);
char LiveElite_TeamSetPrivateProfileFailure(TaskRecord *task);
unsigned __int64 LiveElite_GetTeamID(const ControllerIndex_t localControllerIndex);
bool LiveElite_IsClanAbbrevValidated(const ControllerIndex_t localControllerIndex);
char LiveElite_GetMembersFailure(TaskRecord *task);
char LiveElite_GetClanXPAndLevelSuccess(TaskRecord *task);
char LiveElite_GetClanXPAndLevelFailure(TaskRecord *task);
char LiveElite_GetMembershipFailure(TaskRecord *task);
char LiveElite_GetTeamPublicProfileFailure(TaskRecord *task);
char LiveElite_GetTeamPrivateProfileSuccess(TaskRecord *task);
char LiveElite_GetTeamPrivateProfileFailure(TaskRecord *task);
char LiveElite_ArchiveMarketingOptInSuccess(TaskRecord *task);
char LiveElite_ArchiveMarketingOptInFailure(TaskRecord *task);
char LiveElite_GetSubscriberInfoFromDWSuccess(TaskRecord *task);
char LiveElite_GetSubscriberInfoFromDWFailure(TaskRecord *task);
char LiveElite_RefreshDWSubscriberInfoSuccess(TaskRecord *task);
char LiveElite_RefreshDWSubscriberInfoFailure(TaskRecord *task);
void LiveElite_CreateClanCmd();
void LiveElite_ClanLeaveCmd();
void LiveElite_TeamSetPublicProfileCmd();
void LiveElite_TeamSetPrivateProfileCmd();
void LiveElite_LaunchAppExecutable_f();
void LiveElite_ShowForceEliteCmds_f();
BOOL LiveElite_CheckProgress(const ControllerIndex_t localControllerIndex, eliteStatus_e status);
void LiveElite_GetGoldClanTag(char *out, const char *clanTag, const char *playerName);
char *LiveElite_GetClanTag_VA(bool useGold, const char *clanTag, const char *playerName);
// bool jsonWriter::checkJSON(jsonWriter *notthis, char *strJSON);
// void eventAccumulator::reset(eventAccumulator *notthis);
// void eventAccumulator::setMatchID(eventAccumulator *notthis, unsigned __int64 inputFileID);
// int eventAccumulator::getSegmentJSON(eventAccumulator *notthis, segment *segmentData, char *outBuffer, int outBufferSize);
// BOOL eventAccumulator::canFlush(eventAccumulator *notthis);
char LiveElite_GetMembersSuccess(TaskRecord *task);
char LiveElite_GetMembershipSuccess(TaskRecord *task);
char LiveElite_GetTeamPublicProfileSuccess(TaskRecord *task);
// void jsonWriter::beginObject(jsonWriter *notthis);
// void jsonWriter::writeValue(jsonWriter *notthis, char *strValue, bool isNameValuePair, segment *segmentType);
// void jsonWriter::terminate(jsonWriter *notthis, int minObjectCounter);
// void eventAccumulator::writeCategoryValue(eventAccumulator *notthis, char *strValue, bool isNameValuePair, bool checkDvarAllowedWrite);
// void eventAccumulator::endMatch(eventAccumulator *notthis);
// void eventAccumulator::endCategory(eventAccumulator *notthis);
// bool eventAccumulator::flush(eventAccumulator *notthis);
// void eventAccumulator::flushCheck(eventAccumulator *notthis);
void LiveElite_Clear(const ControllerIndex_t localControllerIndex);
void LiveElite_Init(void *notthis);
// void eventAccumulator::startMatch(eventAccumulator *notthis);
// void eventAccumulator::beginCategory(eventAccumulator *notthis, char *categoryName);
void __noreturn terminate();

//t6/code/src_noserver/live/live_fileshare.cpp
BOOL LiveFileShare_IsReady(ControllerIndex_t controllerIndex, bool allowRead);
int LiveFileShare_GetIndexFromGameType(const char *gameType, const char *zmMapStartLoc);
void LiveFileshare_AddTag(unsigned __int64 priTag, unsigned __int64 secTag, int *numTags, bdTag *tags, const int maxNumTags);
bool LiveFileshare_TagSanityCheck(bdTag *tags, int numTags);
int LiveFileshare_SortByTime(const void *a, const void *b);
int LiveFileshare_SortByType(const void *a, const void *b);
void LiveFileshare_Sort();
char LiveFileshare_GetVoteStatsFailure(TaskRecord *task);
char LiveFileshare_GetViewStatsFailure(TaskRecord *task);
void LiveFileshare_GetStats(const ControllerIndex_t controllerIndex, fileshareStatType_e statType, int offset, unsigned int *lbIDs, int numLBs, const TaskDefinition *taskDef, fileshareState_e nextState);
void LiveFileshare_GetViewStats(const ControllerIndex_t controllerIndex, int offset);
void LiveFileshare_GetVoteStats(const ControllerIndex_t controllerIndex, int offset);
void LiveFileshare_GetSlotDataSuccess(const ControllerIndex_t controllerIndex);
void LiveFileshare_GetSlotDataFailure(const ControllerIndex_t controllerIndex);
void LiveFileshare_GetSlotData(const ControllerIndex_t controllerIndex, int offset);
void LiveFileshare_SetCopyFileName(char *name);
void LiveFileshare_SetCopyFileDescription(char *description);
void LiveFileshare_DeleteFileSuccess(const ControllerIndex_t controllerIndex, int slot);
void LiveFileshare_DeleteFile(const ControllerIndex_t controllerIndex, unsigned __int64 fileID);
void LiveFileshare_GetSummary(const ControllerIndex_t controllerIndex, unsigned __int64 fileID, int size, fileShareLocation location, int (*dataValidationCallback)(const ControllerIndex_t, unsigned __int64, unsigned __int8 *, int));
void LiveFileshare_DownloadSummarySuccess(const ControllerIndex_t controllerIndex);
void LiveFileshare_DownloadSummaryFailure();
void LiveFileshare_DownloadSummary(const ControllerIndex_t controllerIndex);
void LiveFileShare_AbortOperationCmd();
void LiveFileshare_GetSummaryCmd();
void LiveFileshare_AbortSummaryCmd();
void LiveFileshare_CopyFileParams();
void LiveFileshare_DeleteFileCmd();
void LiveFileshare_Invalidate();
void LiveFileshare_Mem_Startup();
char LiveFileshare_GetVoteStatsSuccess(TaskRecord *task);
char LiveFileshare_GetViewStatsSuccess(TaskRecord *task);
void LiveFileshare_UpdateSlots(const ControllerIndex_t controllerIndex, bool finishEarly);
void LiveFileshare_GetSlots(const ControllerIndex_t controllerIndex, const char *groupName);
void LiveFileshare_Copy_TransferSuccess();
char LiveFileshare_Copy_UpdateDescriptorUser(const ControllerIndex_t controllerIndex);
char LiveFileshare_Copy_UpdateDescriptorPooled(const ControllerIndex_t controllerIndex);
void LiveFileshare_Copy_DownloadDescriptorSuccess(const ControllerIndex_t controllerIndex);
void LiveFileshare_CopyFile(const ControllerIndex_t controllerIndex, unsigned __int64 fileID, bool isPooled, int slot);
void LiveFileshare_Update(void *notthis);
void LiveFileshare_GetSlotsCmd();
void LiveFileshare_CopyFileCmd();
void LiveFileshare_Init();
void LiveFileshare_Mem_Shutdown();

//t6/code/src_noserver/live/live_fileshare_cache.cpp
bool Live_FileShare_CacheInit();
void Live_FileShare_CacheShutdown();
char Live_FileShare_IsCached(unsigned __int64 fileID, fileShareLocation location, int *index);
void Live_FileShareCache_AddDescriptor(unsigned __int64 fileID, fileShareLocation location, bdFileMetaData *descriptor);
char Live_FileShareCache_GetDescriptor(unsigned __int64 fileID, fileShareLocation location, bdFileMetaData *descriptor);

//t6/code/src_noserver/live/live_fileshare_search.cpp
char Live_FileshareSearch_ShouldSearch(searchContext_t *context);
void Live_FileshareSearch_PushResultsToLUA();
bool Live_FileshareSearch_GetCounts(const ControllerIndex_t localControllerIndex, unsigned int *inputLeaderboards, int inputLeaderboardCount, const TaskDefinition *taskDef);
bool Live_FileshareSearch_ReadVotesSuccess(TaskRecord *task);
bool Live_FileshareSearch_ReadVotesFailure();
char Live_FileshareSearch_ReadViewsSuccess();
char Live_FileshareSearch_ReadViewsFailure();
void Live_FileshareSearch_ClearContext();
void Live_FileshareSearch_SetContext(searchContext_t *context);
void Live_FileshareSearch_TestCmd();
void Live_FileshareSearch_Init();

//#include "live/live_fileshare_tables.h"

//t6/code/src_noserver/live/live_friends.cpp
int SortABCFriendsUnifiedFunc(const void *a, const void *b);
int SortStatusFriendsUnifiedFunc(const void *a, const void *b);
void FriendsUnified_SortList(const ControllerIndex_t localControllerIndex);
void FriendsUnified_Init();
void FriendsUnified_UpdateList(const ControllerIndex_t localControllerIndex);

//t6/code/src_noserver/live/live_friends_pc.cpp
void Friends_Init();
FriendInfo *Friends_GetFriendInfoByIndex(const ControllerIndex_t controllerIndex, int index);
void Friends_UpdateInvites(ControllerIndex_t controllerIndex);
char Friends_IsFriendByID(ControllerIndex_t controllerIndex, unsigned __int64 id);
bool Friends_IsInCurrentSession(unsigned __int64 id);
int XFriendStatus(const FriendInfo *xfriend);
void XFriendToFriendInfo(const FriendInfo *xfriend, FriendInfo *info);
void Friends_SetInviteInfo(ControllerIndex_t controllerIndex, XSESSION_INFO sessionInfo, unsigned __int64 fromXuid, bool byInvite);
int Friends_GetCount(ControllerIndex_t controllerIndex, int filter, int inverseFilter);
char Friends_GetByID(ControllerIndex_t controllerIndex, unsigned __int64 id, FriendInfo *info);
char Friends_GetByIndex(ControllerIndex_t controllerIndex, int filter, int index, FriendInfo *info, int inverseFilter);
char Friends_Update(ControllerIndex_t controllerIndex);

//t6/code/src_noserver/live/live_groups_dw.cpp
char LiveGroups_SetGroupsComplete(TaskRecord *task);
char LiveGroups_GetGroupID(const char *path, int *offset, GroupSet **gs);
void LiveGroups_JoinGroup(ControllerIndex_t localControllerIndex, const char *path);
bool LiveGroups_IsInGroup(ControllerIndex_t localControllerIndex, const char *path);
void LiveGroups_LeaveGroup(ControllerIndex_t localControllerIndex, const char *path);
unsigned int LiveGroups_GetCount(const char *path);
void LiveGroups_JoinGroup_f();
void LiveGroups_LeaveGroup_f();
void LiveGroups_Dump_f();
void LiveGroups_Init();
void LiveGroups_UpdateGroupMemberships(const ControllerIndex_t localControllerIndex);
void LiveGroups_SetGroups(ControllerIndex_t localControllerIndex);
bool LiveGroups_GetGroupCountsComplete(TaskRecord *task);
void LiveGroups_GetCounts(ControllerIndex_t localControllerIndex);
void LiveGroups_Update(ControllerIndex_t localControllerIndex);

//t6/code/src_noserver/live/live_leaderboards_dedicated.cpp
char *getLbNameString(typeEnumLB type);
lbdef_t *Live_DedicatedLB_GetLBDef(typeEnumLB type);
int getLbColumnIndexForContentPack(int pack);
void ownershipSet(client_t *client, typeEnumLB type);
void Live_DedicatedLB_Ownerhip_Approved(client_t *client);
void Live_DedicatedLB_Ownerhip_Denied(client_t *client);
void Live_DedicatedLB_Ownerhip_Played(client_t *client);
void Live_DedicatedLB_ClientConnected(client_t *client);
void Live_DedicatedLB_ClientDisconnected(client_t *client);
// LeaderboardRow<10> *getFreeLBRow();
char Live_DedicatedLB_WriteSuccess();
void Live_DedicatedLB_Frame();
bool Live_DedicatedLB_ParseLBDef(const char *lbBuf, int lbBufLen);
int Live_DedicatedLB_FetchDefsFailure(const ControllerIndex_t controllerIndex, void *data);
void Live_DedicatedLB_FetchDefsSuccess(const char *a1, int a2);
char Live_DedicatedLB_FetchLBDefs();
void Live_DedicatedLB_Init();

//t6/code/src_noserver/live/live_leaderboard_dw.cpp
TaskRecord *LiveLeaderboard_SetupNestedTask(const TaskDefinition *taskdef, ControllerIndex_t localControllerIndex, TaskRecord *nestedTask, void *payload);
// void LiveLeaderboard_RowDebugPrint(const ControllerIndex_t localControllerIndex, const unsigned __int64 userID, const LeaderboardDef *lbDef, int trackType, LeaderboardRow<10> *lbRow, bool isWriting);
char LiveLeaderboard_ReadStatsDataFailure(TaskRecord *task);
char LiveLeaderboard_ReadGhostLBFailure(TaskRecord *task);
BOOL LiveLeaderboard_IsGhostLBFetchingFinished();
int LiveLeaderboard_GetGhostLBReadBeginTime();
int LiveLeaderboard_CalculatePlayerLbRowValue(const ControllerIndex_t localControllerIndex, const LeaderboardDef *lbDef, int colIdx);
// char LiveLeaderboard_UploadPlayerDataExecuteTask(const ControllerIndex_t localControllerIndex, const TaskDefinition *taskDef, LeaderboardRow<10> *lbRows, const int uploadRows);
char LiveLeaderboard_WriteStatsDataSuccess();
char LiveLeaderboard_CanUserAccessLeaderboard(const ControllerIndex_t localControllerIndex);
bool LiveLeaderboard_IsUploadedZombie(const ControllerIndex_t localControllerIndex);
void LiveLeaderboard_SetUploadedStatusZombie(const ControllerIndex_t localControllerIndex, bool isUploaded);
void LiveLeaderboard_SetWriteLeaderboards(const LocalClientNum_t localClientNum, const char *lbConfigStr);
int LiveLeaderboard_CompareXUserStatsRowRanks(const void *r1, const void *r2);
void LiveLeaderboard_SortXUserStatsByRank(Leaderboard *lb);
void LiveLeaderboard_ReadStatsSuccess(ControllerIndex_t localControllerIndex, Leaderboard *lb);
char LiveLeaderboard_GetStatsByXuidsFailure(TaskRecord *task);
char __cdecl LiveLeaderboard_GetByRank(Leaderboard *lb, const ControllerIndex_t localControllerIndex, const unsigned int rankIndex);
char LiveLeaderboard_GetByRankFailure(TaskRecord *task);
char LiveLeaderboard_GetByPlayerFailure(TaskRecord *task);
bool LiveLeaderboards_GetResetLeaderboards(const char *resetFile, const char **leaderboards, int *leaderboardCount);
ControllerIndex_t LiveLeaderboard_SortMultiSearchResults(ControllerIndex_t localControllerIndex);
int LiveLeaderboard_lbGetCache(const ControllerIndex_t controllerIndex, const int colIndex);
char LiveLeaderboard_ReadStatsDataSuccess(TaskRecord *task);
char LiveLeaderboard_ReadGhostLBSuccess(TaskRecord *task);
// int LiveLeaderboard_ColumnIDToValue(const LeaderboardDef *lbDef, LeaderboardRow<10> *row, int colId);
// int LiveLeaderboard_MakeRow(const ControllerIndex_t localControllerIndex, const LeaderboardDef *lbDef, LeaderboardRow<10> *const row, LbAggType aggType, unsigned __int64 userID);
// bool LiveLeaderboard_RankUpdate(const ControllerIndex_t localControllerIndex, const unsigned __int64 userID, const LeaderboardDef *lbDef, LeaderboardRow<10> *lbRow, const int aggType, const int trackType, int *uploadRows);
// bool LiveLeaderboard_CombineUpdate(const ControllerIndex_t localControllerIndex, const unsigned __int64 userID, const LeaderboardDef *lbDef, LeaderboardRow<10> *lbRow, const int trackType, int *uploadRows);
// char LiveLeaderboard_UploadPlayerDataExecuteBlockingTask(const ControllerIndex_t localControllerIndex, LeaderboardRow<10> *lbRows, const int uploadRows);
char LiveLeaderboard_WriteStatsDataFailure(TaskRecord *task);
char LiveLeaderboard_UploadPlayerStatsExecute(const ControllerIndex_t localControllerIndex);
char LiveLeaderboard_UploadPlayerStats(const ControllerIndex_t localControllerIndex);
char LiveLeaderboard_GetStatsSuccess(TaskRecord *task);
char LiveLeaderboard_GetStatsByXuidsSuccess(TaskRecord *task);
char LiveLeaderboard_GetByPlayerSuccess(TaskRecord *task);
char LiveLeaderboards_ResetLeaderboardsClearRows(const ControllerIndex_t controllerIndex, const char **leaderboards, int leaderboardCount);
void LiveLeaderboards_ResetLeaderboards(const char **a1, char *a2, const ControllerIndex_t controllerIndex);
void LiveLeaderboards_ResetLeaderboards_f();
void LiveLeaderboard_Init();
char LiveLeaderboard_GetMiniLbsSuccess(TaskRecord *task);

//t6/code/src_noserver/live/live_leagues.cpp
void ParseError(jsmntok_t *token, const char *msg);
void DataError(jsmntok_t *token, const char *msg);
jsmntok_t *GetNextToken(jsmntok_t **token, jsmntok_t *end);
jsmntok_t *GetEndToken(jsmntok_t *token);
char GetNextKeyValue(jsmntok_t **token, jsmntok_t *end, jsmntok_t **key, jsmntok_t **value);
bool IsTokenEqual(jsmntok_t *token, const char *str);
char *GetTokenString(jsmntok_t *token);
const GfxViewParms *CopyTokenString(jsmntok_t *token);
const GfxViewParms *CopyTokenLocalizedString(jsmntok_t *token);
int GetTokenInt(jsmntok_t *token);
float GetTokenFloat(jsmntok_t *token);
bool GetTokenBool(jsmntok_t *token);
int GetTokenTime(jsmntok_t *token);
char ParseSeasons(League *league, jsmntok_t *token);
char ParseIcons(LeagueDivision *division, jsmntok_t *token);
char ParseAwards(League *league, jsmntok_t *token);
char ParseNouns(jsmntok_t *token);
char ParseNumbers(jsmntok_t *token);
char ParseLeagues(jsmntok_t *token);
char ParseDivisions(jsmntok_t *token);
void ResetLeagueInfo();
bool ValidateLeagueInfo();
bool CheckTokenizerError(jsmnerr_t result);
bool ParseLeagueInfo(const char *buffer);
int League_GetCurrentID();
char League_ParseInfo(const char *buffer);
int League_GetTeamSize(int id);
LeagueSeason *League_GetSeasonByID(int leagueID, int seasonID);
LeagueSeason *League_GetActiveSeason(int id);
LeagueSeason *League_GetNextActiveSeason(int id);
LeagueDivision *League_FindDivision(int id, int divisionID);
char League_GetTeamIDFailure(TaskRecord *task);
void League_Backoff(ControllerIndex_t controllerIndex);
void League_SetupDefaultStats(StatsLookup *lookup);
void League_PushStats(LeagueStats *stats, bdLeagueStatsInfo *dwStats);
void League_MSGWriteStats(msg_t *msg, const LeagueStats *stats);
void League_MSGReadStats(msg_t *msg, LeagueStats *stats);
char League_GetStatsFailure(TaskRecord *task);
char League_FetchTeamsListFailure();
char LeagueFetchSoloTeamIDFailure();
char League_FetchTeamSubdivisionsSuccess(TaskRecord *task);
char League_FetchTeamSubdivisionsFailure(TaskRecord *task);
char League_FetchTeamInfoFailure();
char League_FetchLbTeamMemberInfoFailure();
char League_FetchTeamMemberInfoSuccess(TaskRecord *task);
char League_FetchTeamMemberInfoFailure();
int SortSubdivisionInfosBySeasonDate(const void *a, const void *b);
char League_FetchHistorySubdivisionInfosFailure();
char League_FetchLeagueHistoryFailure();
bool ParseMetaData(unsigned __int8 *metaData, int metaDataLength, int *divisionID, int *nameID, bool *isSolo);
char League_FetchSubdivisionFailure(TaskRecord *task);
char League_RefetchSubdivisionSuccess(bool *a1, TaskRecord *task);
char League_RefetchSubdivisionFailure(TaskRecord *task);
void League_ClearTeamTasks(const ControllerIndex_t controllerIndex);
char League_GetCurrentTeamID(const ControllerIndex_t controllerIndex, unsigned __int64 *teamID, int *memberCount, unsigned __int64 *subdivisionID, int *divisionID);
bool League_SetOutcomes(const ControllerIndex_t controllerIndex, const LeagueOutcomes *outcomes);
void League_SetMatchDelta(StatsLookup *lookup, LeagueStats *outcomeStats, LeagueStats *baseStats);
char League_AreWeFetchingStats(const ControllerIndex_t controllerIndex);
char League_FetchLbDataFailure(TaskRecord *task);
char League_FindTeamAndLeagueInFetchedData(const ControllerIndex_t controllerIndex, unsigned __int64 teamID, int leagueID, unsigned __int64 *subdivisionID, bool *inPlacement);
char League_FetchAllInfoForTeamInLeagueFailure();
void League_RecordEvent(const ControllerIndex_t controllerIndex, const char *eventName, unsigned __int64 uniqueID);
const GfxViewParms *League_GetCurrentTeamName(const ControllerIndex_t controllerIndex);
void League_Status(const ControllerIndex_t controllerIndex);
bool League_GetSkillAndVariance(const ControllerIndex_t controllerIndex, float *skill, float *variance);
char League_GetCurrentStats(const ControllerIndex_t controllerIndex, LeagueStats *stats);
void League_Status_f();
void League_Refresh_f();
char League_HandleInstantMessage(ControllerIndex_t controllerIndex, const char *msg);
void League_CalculateScore(League *league, int count, LeagueTeam *teams);
void League_CalculateMatchResult(int count, LeagueTeam *teams);
char League_GetTeamID(const ControllerIndex_t controllerIndex, const unsigned __int64 *members, int memberCount, unsigned __int64 *result);
void League_UpdateBonusAllocation(ControllerIndex_t controllerIndex);
char League_GetStatsSuccess(TaskRecord *task);
bool League_FetchTeamsListInternal(const ControllerIndex_t controllerIndex, int offset, int numResultsToFetch);
char __cdecl LeagueFetchSoloTeamIDSuccess(TaskRecord *task);
bool League_FetchSoloTeamID(const ControllerIndex_t controllerIndex);
bool __cdecl League_FetchTeamsList(const ControllerIndex_t controllerIndex, int offset, int numResultsToFetch, unsigned __int64 xuid);
char League_FetchTeamInfo(const ControllerIndex_t controllerIndex);
char League_FetchTeamMemberInfo(const ControllerIndex_t controllerIndex);
char League_FetchHistorySubdivisionInfosSuccess(TaskRecord *task);
void League_FetchLeagueHistorySubdivisionInfos(const ControllerIndex_t controllerIndex);
char League_FetchLeagueHistoryInternal(const ControllerIndex_t controllerIndex, unsigned __int64 teamID, __int16 currLeagueIndex);
char League_FetchLeagueHistorySuccess(TaskRecord *task);
char League_FetchSubdivisionSuccess(bool *a1, TaskRecord *task);
char League_UploadStatsSuccess(TaskRecord *task);
char League_UploadStatsFailure(TaskRecord *task);
void League_SetCurrentTeamID(const ControllerIndex_t controllerIndex, int leagueID, unsigned __int64 teamID, int memberCount);
char League_ApplyOutcome(bdLeagueStatsInfo *a1, StatsLookup *a2, const ControllerIndex_t controllerIndex, LeagueOutcome outcome, int leagueHash);
char League_FetchLbDataSuccess(TaskRecord *task);
char League_FetchLbDataByPivot(const ControllerIndex_t controllerIndex, unsigned __int64 teamID, unsigned __int64 subdivisionID, int numResults);
char League_FetchLbDataByRank(const ControllerIndex_t controllerIndex, unsigned __int64 subdivisionID, int numResults, int offset);
bool League_SetCurrentTeamEmblem(const ControllerIndex_t controllerIndex, CompositeEmblemLayer *layers, int layerCount, unsigned __int64 teamID);
void League_Force_f();
void League_Fake_f();
char League_FetchTeamsListSuccess(TaskRecord *task);
char League_FetchLbData(const ControllerIndex_t controllerIndex, unsigned __int64 teamID, unsigned __int64 subdivisionID, int numResults, int offset);
char League_FetchAllInfoForTeamInLeagueSuccess(TaskRecord *task);
void League_FetchLbData_f();
void League_Init();
void ParseError(const char *msg);

//t6/code/src_noserver/live/live_league_friends.cpp
void League_Friends_TeamMemberInfoDownloaded(const ControllerIndex_t controllerIndex, const LeagueTeamsData *leagueTeamsData);

//t6/code/src_noserver/live/live_metplayer.cpp
void LiveMetPlayer_ClearUploadFlags(const ControllerIndex_t controllerIndex);
bool LiveMetPlayer_UploadMetPlayerListNeeded(ControllerIndex_t controllerIndex);
void LiveMetPlayer_ResetData(ControllerIndex_t controllerIndex);
void LiveMetPlayer_RemoveFriendsFromRecentPlayerList(ControllerIndex_t controllerIndex);
void LiveMetPlayer_UploadMetPlayerList(ControllerIndex_t localControllerIndex);
void LiveMetPlayer_RemoveFriendsFromRecentPlayerListCmd();
void LiveMetPlayer_Init();
char LiveMetPlayer_GetIndexByXUID(ControllerIndex_t controllerIndex, unsigned __int64 xuid, int *index);
char LiveMetPlayer_GetRecentPlayerInfoByID(ControllerIndex_t controllerIndex, unsigned __int64 id, XuidInfo *recentMetPlayerInfo);

//t6/code/src_noserver/live/live_presence_win.cpp
unsigned int offsetOfBufInHunkUserDefault(bdChannelInfo *notthis);
void Live_Disconnected();
void Live_NotPlaying();
void Live_SetLobbyPresence();
void Live_SetPartyPresence();
void Live_SetGeographicalRegion();
void Live_SetPlaylistVersion(ControllerIndex_t controllerIndex);
void Live_SetPlaylistNum(ControllerIndex_t localControllerIndex, int playlistNum);
void Live_SetGametype(ControllerIndex_t localControllerIndex, const char *gametype);
void Live_SetZmLocationContext(ControllerIndex_t localControllerIndex, const char *zmLocation);
int Live_GetMapIndex(const char *mapname);
void Live_SetCurrentMapname(const char *mapname);
void Live_SetTeamSizeRange(const int teamMaxSize);
int Live_GetMapSource(const int mapIndex);
void Live_SetMapPacks(const int mapPacks);
void Live_SetCurrentGametype();
void Live_SetTheaterPlayingPresence();

//t6/code/src_noserver/live/live_sessions.cpp
int Session_BuildQoSPayload(SessionData *session);
unsigned __int8 *Session_GetQosPayloadBuffer();
void Session_UpdateQoSPayload(SessionData *session);
char GetQoSPayload(unsigned __int8 *data, int dataSize, qosPayload_t *qosPayload);
ClientNum_t Session_HostNum(SessionData *session);
bool Session_IsLocalMember(SessionData *session, const ClientNum_t clientNum);
void Session_CloseJoinSessionPopup(ControllerIndex_t controllerIndex);
netadr_t *Live_GetPlayerAddr(netadr_t *result, SessionData *session, const ClientNum_t clientNum);
BOOL Live_PlayerHasLoopbackAddr(SessionData *session, const ClientNum_t clientNum);
ClientNum_t Session_FindRegisteredUser(const SessionData *session, const unsigned __int64 xuid);
bool Session_IsUserRegistered(const SessionData *session, const ClientNum_t clientNum);
unsigned __int64 Session_GetXuid(const SessionData *session, const ClientNum_t clientNum);
unsigned __int64 Session_GetXuidEvenIfInactive(const SessionData *session, const ClientNum_t clientNum);
netadr_t *Live_GetPlayerNetAddr(netadr_t *result, const SessionData *session, const ClientNum_t clientNum);
bool Live_IsClientRegistered(const SessionData *session, const ClientNum_t clientNum);
ClientNum_t Live_GetOurClientNum(ControllerIndex_t controllerIndex, SessionData *session);
int Session_CurrentFlags(SessionData *session);
int Session_PublicSlots(const SessionData *session);
int Session_PrivateSlots(SessionData *session);
unsigned __int64 Session_GetNonce(SessionData *session);
void Session_SetNonce(SessionData *session, unsigned __int64 nonce);
XSESSION_INFO *Session_GetXNKId(SessionData *session);
bool Session_Started(SessionData *session);
void Live_UpdatePlayerNetAddr(SessionData *session, const ClientNum_t clientNum, const netadr_t *addr);
void Live_UpdatePlayerInAddr(SessionData *session, const ClientNum_t clientNum, const in_addr inaddr, const unsigned __int16 port);
void Live_UpdatePlayerAddr(SessionData *session, const ClientNum_t clientNum, const netadr_t addr);
void Session_Init();
void Session_QoSListenStart(SessionData *session);
bool Session_IsControllerValidForCreatingSession(ControllerIndex_t controllerIndex, int requiredSigninState);
int Session_GetSessionCreateController(int requiredSigninState);
char Session_StartClient(SessionData *session, const ControllerIndex_t localControllerIndex, const int flags, XSESSION_INFO *hostInfo, unsigned __int64 sessionNonce, int numPublicSlots, int numPrivateSlots);
bool Session_NeedToSyncParams(SessionData *session, const int numPublic, const int numPrivate, const int flags);
bool Session_ModifyInProgress();
bool Session_CreateInProgress();
bool Session_SearchInProgress();
void Session_CheckSessionTaskBySession(TaskRecord *task, void *inData);
char Session_SessionTasksInProgress(SessionData *session);
bool Session_CreateInProgress(SessionData *session);
void Session_CancelIndividualSessionTasks(SessionData *session);
void Session_CancelSessionTasks(SessionData *session);
void Session_WaitOnSessionTasks(SessionData *session);
void Session_WaitForTaskToComplete(TaskRecord *sessionTask, int startTime, int timeOut);
void Session_FinishOngoingSessionJoinTasksForXUID(const char *a1, SessionData *session, unsigned __int64 player);
SessionData *Session_GetCurrentSession();
void Session_UnregisterRemotePlayer(SessionData *session, const ClientNum_t slot);
void Session_EndGameSession(SessionData *session);
int Session_GetFreeSessionGraveYardSlot();
void Session_DeleteSession(SessionData *session, bool deleteNow);
void Session_DeleteSession(SessionData *session);
void Session_StartHost(SessionData *session, int sessionFlags, int numPrivateSlots, int numPublicSlots, bool silentFail);
void Session_FinishModify(void);
void Session_StartGameSession(const ControllerIndex_t localControllerIndex, SessionData *session);
void Session_RemoveAllPlayersFromSession(SessionData *session);
void Session_CleanUpSearches(const char *a1);
void Session_EmptyGraveYard();
void Session_EndOngoingSessionTasksForLeave(SessionData *session);

//t6/code/src_noserver/live/live_sessions_delegate.cpp
void HostDelegate_UpdateState(hostDelegationState_t newState);
BOOL HostDelegate_AreWeSessionOwner();
BOOL HostDelegate_ShouldSendPartyState();
void HostDelegate_RegisterPlayer(unsigned __int64 playerXUID, netadr_t playerAddr);
char HostDelegate_CurrentlyDelegating();
char anyPotentialDelegates();
void cleanupSessionDetails();
void HostDelegate_UnregisterPlayer(unsigned __int64 playerXUID);
char HostDelegate_Choose();
BOOL HostDelegate_IsCurrentHostValid();
bool sendHostDelegateCmd(netadr_t to);
char HostDelegate_ResendDelegateCmd();
void HostDelegate_Frame();
BOOL packetIsFromDelegate(netadr_t from);
void hostDelegateHandleSessionCreate(netadr_t from, const ControllerIndex_t controllerIndex, msg_t *msg, unsigned __int8 flags);
void HostDelegate_Init();
void HostDelegate_HandlePacket(LocalClientNum_t clientNum, netadr_t from, msg_t *msg);

//t6/code/src_noserver/live/live_sessions_dw.cpp
void Session_DeleteDWSession();
char Session_DeleteSessionSuccess();
char Session_DeleteSessionFailure();
void Session_QoSUpdate_Platform();
void Session_QoSListenStart_Platform(SessionData *session);
void Session_QoSListenStop(SessionData *session);
char Session_CreateHostSessionFailure(TaskRecord *task);
char Session_CreateNonMatchmakingSessionFailure(TaskRecord *task);
char Session_CreateNonMatchmakingSessionSuccess(TaskRecord *task);
bool Session_StartClient_Platform(SessionData *session, const ControllerIndex_t localControllerIndex, const int flags, XSESSION_INFO *hostInfo);
void Session_Modify(const ControllerIndex_t localControllerIndex, SessionData *session, const int flags, const int publicSlots, const int privateSlots);
char Session_ModifySessionSuccess(TaskRecord *task);
void Session_JoinSession(const ControllerIndex_t localControllerIndex, SessionData *session, const int slot, const unsigned __int64 player, bool privateSlot);
void Session_LeaveSession(SessionData *session, const ClientNum_t registeredUserSlot);
void Session_RegisterRemotePlayer(const ControllerIndex_t localControllerIndex, SessionData *session, const unsigned __int64 player, bool privateSlot, const ClientNum_t clientNum, const int natType, const netadr_t addr);
void Session_EveryoneLeaveSessionAsync(const ControllerIndex_t localControllerIndex, SessionData *session);
TaskRecord *Session_StartHostCreateTask_Platform(ControllerIndex_t controllerIndex, int sessionFlags);
int Session_StartHost_Platform_DW(SessionData *session, int sessionFlags, int numPrivateSlots, int numPublicSlots, ControllerIndex_t controllerIndex, TaskRecord *sessionCreateTask);
void Session_ChangeAdvertisedStatus(bool onOff, bool force);
void Live_SetSkill(const float skill);
void Session_StartDeleteHandle(SessionData *session);
char Session_CreateHostSessionSuccess(TaskRecord *task);
int Session_CreateNonMatchmakingSession(TaskRecord *task);
char Session_ModifySessionFailure(TaskRecord *task);
char Session_FindSessionsFailure(TaskRecord *task);
char Session_FindSessionsSuccess(TaskRecord *task);

//t6/code/src_noserver/live/live_sessions_win.cpp
int Session_StartHost_Platform(SessionData *session, int sessionFlags, int numPrivateSlots, int numPublicSlots, ControllerIndex_t controllerIndex, TaskRecord *sessionCreateTask);
void Session_Init_Platform();

//t6/code/src_noserver/live/live_stats.cpp
bool LiveStats_IsUsingLoadoutStats();
unsigned int LiveStats_GetDDLHeaderVersion(unsigned __int8 *statsBuffer);
int LiveStats_CanPerformStatOperation(ControllerIndex_t controllerIndex);
int LiveStats_GetStat(const ControllerIndex_t controllerIndex, ddlState_t *searchState, statsLocation location, ddlValue_t *result);
int LiveStats_GetUIntStat(const ControllerIndex_t controllerIndex, ddlState_t *searchState, statsLocation location);
ddlValue_t LiveStats_GetInt64Stat(const ControllerIndex_t controllerIndex, ddlState_t *searchState, statsLocation location);
const GfxViewParms *LiveStats_GetStringStat(const ControllerIndex_t controllerIndex, ddlState_t *searchState, statsLocation location);
bool LiveStats_GetStatsDDLSizeByFile(const char *ddlFileName, int version, int *size);
unsigned int LiveStats_ChecksumGamerStats(unsigned __int8 *buffer, const int len);
void LiveStats_SetDInt64StatFromBuffer(unsigned __int8 *buffer, ddlState_t *searchState, const unsigned __int64 value);
void LiveStats_SetDInt64Stat(char *a1, const ControllerIndex_t controllerIndex, ddlState_t *searchState, const unsigned __int64 value);
bool LiveStats_IsStableStatsBufferInitialized(const ControllerIndex_t controllerIndex);
void LiveStats_SetItemStat(ddlState_t *searchStateStats, const char *statMember, unsigned __int8 *buffer, unsigned int value);
unsigned int LiveStats_GetItemStat(ddlState_t *searchStateStats, const char *statMember, unsigned __int8 *buffer);
const char *LiveStats_GameHistory_GetModeName();
unsigned int LiveStats_GameHistory_GetMatchStatUInt(ddlState_t *searchState, unsigned __int8 *liveStatsBuffer, matchHistoryKeyIndex_t key);
bool LiveStats_GameHistory_SetMatchStatUInt(ddlState_t *searchState, unsigned __int8 *liveStatsBuffer, matchHistoryKeyIndex_t key, unsigned int value, ddlState_t *searchState2);
bool LiveStats_GameHistory_SetMatchStatFloat(ddlState_t *searchState, unsigned __int8 *liveStatsBuffer, matchHistoryKeyIndex_t key, float value, ddlState_t *searchState2);
void LiveStats_GameHistory_InitializeHitLocationsArray(ClientNum_t clientNum, ddlState_t *recentHitLocSearchState, unsigned __int8 *liveStatsBuffer, const char *arrayName);
void LiveStats_Probation_GetProbationQuitTypeCost(eGameModes gamemode, float (*quitTypeCost)[5]);
bool StringBeginsWith(const char *prefix, const char *name);
int LiveStats_GetNumRecentlyUnlockedItems(ControllerIndex_t controllerIndex);
int LiveStats_GetRecentlyUnlockedItemIndex(ControllerIndex_t controllerIndex, unsigned int itemNum);
unsigned int LiveStats_CompressStats(const ControllerIndex_t controllerIndex, unsigned __int8 *compressedBuffer, int compressedBufferSize);
void LiveStats_DecompressStats(unsigned __int8 *statsDestBuffer, int numCompressedPackets);
BOOL LiveStats_ValidateChecksum(unsigned __int8 *buffer, const int len);
BOOL LiveStats_ValidateBuffer(unsigned __int8 *buffer, int bufferSize);
char LiveStats_ParsePathToState(const char *path, ddlState_t *destState);
unsigned __int8 LiveStats_GetRecentUnlocks(const ControllerIndex_t controllerIndex);
double LiveStats_UpdateSkillAndVariance_Score(int count, PlayerSkill *players);
void LiveStats_SkillTestCmd();
bool LiveStats_CheckValidDelta(statsDelta_t *delta, int currentDelta);
void LiveStats_CheckForModUnlocks(const ControllerIndex_t controllerIndex, int itemNumber, unsigned __int8 *liveStatsBuffer, unsigned __int8 *oldStatsBuffer);
void LiveStats_CheckForTokenUnlocks(const ControllerIndex_t controllerIndex, int startingRank, int endingRank);
bool LiveStats_HasRecentItemAttachmentsUnlocked(const ControllerIndex_t controllerIndex, unsigned int itemIndex);
bool LiveStats_IsItemAttachmentRecentlyUnlocked(const ControllerIndex_t controllerIndex, unsigned int itemIndex, eAttachment attachment);
void LiveStats_StatReadDDLCommand(int cmdArgcStartPos, statsLocation statsLoc);
void LiveStats_StatReadDDLExtCmd();
void LiveStats_StatReadDDLCmd();
void LiveStats_StatWriteDDLCmdInternal(bool localize);
void LiveStats_StatWriteDDLCmd();
void LiveStats_StatWriteFromLocalizedStrCmd();
void LiveStats_ClearCustomClassWarning(const ControllerIndex_t controllerIndex);
void LiveStats_ClearStatsWarning(const ControllerIndex_t controllerIndex);
bool LiveStats_CheckClassVersion(const ControllerIndex_t controllerIndex);
ddlState_t *LiveStats_GetRootDDLState();
ddlDef_t *LiveStats_GetStatsDDL();
ddlDef_t *LiveStats_GetClassSetsDDL();
const CACRoot *LiveStats_GetCACRoot(const CACRoot *result, const ControllerIndex_t controllerIndex, statsLocation playerStatsLocation);
const CACRoot *LiveStats_GetCACRoot(const CACRoot *result, unsigned __int8 *buffer);
const CACRoot *LiveStats_GetCustomMatchCACRoot(const CACRoot *result, const ControllerIndex_t controllerIndex);
const CACRoot *LiveStats_GetLeagueCACRoot(const CACRoot *result, const ControllerIndex_t controllerIndex);
char LiveStats_WriteXUIDToStats(const ControllerIndex_t controllerIndex);
void LiveStats_ClearXUIDInStableStats(const ControllerIndex_t controllerIndex);
unsigned int LiveStats_ReadXUIDFromStatsBuffer(unsigned __int8 *buff);
void LiveStats_SetBufferInitialised(const ControllerIndex_t controllerIndex, bool isInitialised);
void LiveStats_SetOnlineRankedState(unsigned __int8 *buffer, bool value);
bool LiveStats_GetOnlineRankedState(unsigned __int8 *buffer);
void LiveStats_SetOnlineZombieState(unsigned __int8 *buffer, bool value);
bool LiveStats_GetOnlineZombieState(unsigned __int8 *buffer);
BOOL LiveStats_IsSettingOnlineStatsAllowed();
void LiveStats_GetNemesisXuid(const ControllerIndex_t controllerIndex, unsigned __int64 *nemesisXuid);
int LiveStats_MoveToDemonwareFlags(ddlState_t *searchState, demonwareFlags_e flags);
void LiveStats_SetDemonwareFlag(const ControllerIndex_t controllerIndex, demonwareFlags_e flags, int value);
void LiveStats_CheckPrestigeFiles(const ControllerIndex_t controllerIndex);
void LiveStats_BackupAllStats(unsigned __int8 *inBuffer, unsigned __int8 *outBuffer);
void LiveStats_PrestigeAddCACCmd();
bool LiveStats_ParsePathToDeltaState(const char *path, int currentDelta);
void LiveStats_BuildStatsDeltaTable();
char *LiveStats_GetGameTypeString();
int LiveStats_MoveToPlayerStatPath(ddlState_t *resultState, const char *statName, const char *statType);
int LiveStats_MoveToCurrentGameTypeStatPath(ddlState_t *resultState, const char *statName, const char *statType, bool isGroup);
int LiveStats_MoveToWeaponStatPathZombie(ddlState_t *resultState, int weaponStatIndex, const char *statName, const char *statType);
int LiveStats_MoveToWeaponStatPath(ddlState_t *resultState, int weaponStatIndex, const char *statName, const char *statType);
int LiveStats_MoveToWeaponXPPath(ddlState_t *resultState, int weaponStatIndex);
int LiveStats_MoveToAttachmentStatPathZombie(ddlState_t *resultState, int attachmentIndex, const char *statName, const char *statType);
int LiveStats_MoveToAttachmentStatPath(ddlState_t *resultState, int attachmentIndex, const char *statName, const char *statType);
int LiveStats_MoveToGroupStatPathZombie(ddlState_t *resultState, int groupIndex, const char *statName, const char *statType);
int LiveStats_MoveToGroupStatPath(ddlState_t *resultState, int groupIndex, const char *statName, const char *statType);
int LiveStats_MoveToUnlockPath(ddlState_t *resultState, int tokenIndex);
void ddlTestFixedPoint_f();
void ddlTestFloat_f();
void ddlTestBool_f();
ddlState_t *LiveStats_GetRankXPState();
void LiveStats_SetMOTDViewed(const ControllerIndex_t controllerIndex, int viewTime, int viewVersion);
void LiveStats_SetMOTDViewedCmd();
void LiveStats_SetVotingDemonwareFlags(const ControllerIndex_t controllerIndex, demonwareFlags_e flags, int value);
void LiveStats_IncrementVotingMenuViewedCount(const ControllerIndex_t controllerIndex);
void LiveStats_SetDemonwareFlagsWithUTCTime(ControllerIndex_t controllerIndex, int demonwareFlagsStartIndex, int demonwareFlagsEndIndex);
void __cdecl LiveStats_SetVotingMenuViewedCmd();
void LiveStats_SetVoteCmd();
void LiveStats_SetVoteOptOutCmd();
void __cdecl LiveStats_SetDSPPromotionOptOutCmd();
void LiveStats_SetDSPPromotionViewedCmd();
void __cdecl LiveStats_SetGhostUpsellOptOutCmd();
void LiveStats_SetGhostUpsellViewedCmd();
void LiveStats_SetSPReminderViewedCmd();
void LiveStats_SetupStates();
void LiveStats_InitGameTypes();
int LiveStats_GetGameTypeIndex(const char *gameTypeRef, bool isHardcore);
int LiveStats_GetGameTypeIndexFromRef(const char *gameTypeRef);
int LiveStats_GetGameTypeNameHash(int index);
char *LiveStats_GetGameTypeName(int index);
void LiveStats_UpdateContentData(const ControllerIndex_t controllerIndex);
int LiveStats_GetStatsDDLSize();
char LiveStats_ShouldSetStats();
int LiveStats_GetIntPlayerStatInternal(int pathDepth, const char **statPath, unsigned __int8 *buffer);
int LiveStats_GetIntStatFromPath(const char *statPath, unsigned __int8 *buffer);
int LiveStats_GetIntPlayerStatFromBuffer(const char *statName, unsigned __int8 *buffer);
int LiveStats_GetIntPlayerStatFromPath(const ControllerIndex_t controllerIndex, const char *statPath);
int LiveStats_GetIntPlayerStat(const ControllerIndex_t controllerIndex, const char *statName);
int LiveStats_GetIntPlayerStatByMap(const ControllerIndex_t controllerIndex, const char *map, const char *statName);
int LiveStats_GetIntPlayerStatByKey(const ControllerIndex_t controllerIndex, playerStatsKeyIndex_t keyIndex);
bool LiveStats_SetIntPlayerStatInternal(const ControllerIndex_t controllerIndex, int pathDepth, const char **path, unsigned __int8 *buffer, unsigned int statValue);
int LiveStats_GetIntPlayerStatMatchDelta(const ControllerIndex_t controllerIndex, const char *statName);
int LiveStats_GetIntPlayerStatMatchDeltaFromPath(const ControllerIndex_t controllerIndex, const char *statPath);
bool LiveStats_SetIntPlayerStat(const ControllerIndex_t controllerIndex, const char *statName, unsigned int statValue);
bool LiveStats_SetIntPlayerStatByMap(const ControllerIndex_t controllerIndex, const char *map, const char *statName, unsigned int statValue);
int LiveStats_GetPlayerStatByKeyFromBuffer(playerStatsKeyIndex_t key, unsigned __int8 *buffer);
int LiveStats_GetStatsVersion(const ControllerIndex_t localControllerIndex);
void LiveStats_RestoreStatsFromStable(const ControllerIndex_t controllerIndex, statsLocation initialStats, statsLocation currentStats);
void LiveStats_SecurityErrorDetected(const ControllerIndex_t controllerIndex);
void LiveStats_SetStatByKey(unsigned int a1, const ControllerIndex_t controllerIndex, playerStatsKeyIndex_t keyIndex, const int value);
void LiveStats_StatSetByNameCmd(unsigned int a1);
void LiveStats_StatAddByNameCmd();
void LiveStats_StatGetByNameInDvarCmd();
char LiveStats_CheckXUIDAndReport(const ControllerIndex_t controllerIndex);
unsigned int LiveStats_GetPlayerStat(const char *statsList, const char *statName, unsigned __int8 *buffer);
int LiveStats_GetLastGameWeaponStat(unsigned __int8 *liveStatsBuffer, unsigned __int8 *oldStatsBuffer, const char *weaponStatType, int itemNumber);
void __cdecl LiveStats_UpdateBestWeaponIndexAAR(unsigned __int8 *liveStatsBuffer, unsigned __int8 *oldStatsBuffer);
void LiveStats_SetPlayerStat(const char *statsList, const char *statName, unsigned __int8 *buffer, unsigned int statValue);
bool LiveStats_UpdatetBestMatchAccuracy(unsigned __int8 *liveStatsBuffer, unsigned __int8 *oldStatsBuffer);
bool LiveStats_UpdatetBestMatchKdRatio(unsigned __int8 *liveStatsBuffer, unsigned __int8 *oldStatsBuffer);
void LiveStats_GameHistory_GetCompletionInfo(const ControllerIndex_t localControllerIndex, const char *gamemode, const char *hostedType, unsigned int *started, unsigned int *completed, unsigned int *quit, unsigned int *timeout, unsigned int *dashboard);
bool LiveStats_GameHistory_IncCompletionStat(const ControllerIndex_t localControllerIndex, const char *gamemode, const char *hostedOrPlayed, const char *statName);
void LiveStats_GameHistory_AddMatchHistory(const ControllerIndex_t localControllerIndex, const char *statName, bool hosted);
void LiveStats_GameHistory_AddMatchCompleted(const ControllerIndex_t localControllerIndex, bool hosted);
void LiveStats_GameHistory_AddMatchTimeout(const ControllerIndex_t localControllerIndex, bool hosted);
void __cdecl LiveStats_GameHistory_InitializeMatchHistory(ClientNum_t clientNum, unsigned int gameTypeIndex);
void LiveStats_GameHistory_InitializeHitLocations(char *a1, ClientNum_t clientNum);
void LiveStats_GameHistory_StartMatch(ClientNum_t clientNum, unsigned int gameTypeIndex);
bool LiveStats_GameHistory_MoveToCurrentHistory(unsigned __int8 *liveStatsBuffer, ddlState_t *matchHistorySearchState, unsigned int *matchHistoryIndex);
bool LiveStats_GameHistory_MoveToHistory(unsigned __int8 *liveStatsBuffer, const char *gamemode, ddlState_t *matchHistorySearchState, unsigned int matchHistoryIndex);
void LiveStats_GameHistory_FinishMatch(char *a1, unsigned int a2, ClientNum_t clientNum, int finishType, int kills, int deaths, int score, int scoreboardPosition, float teamScoreRatio);
void LiveStats_GameHistory_FinishMatch(ddlState_t *a1, const ControllerIndex_t controllerIndex, int finishType);
char LiveStats_Probation_GiveProbation(const ControllerIndex_t controllerIndex, eGameModes gamemode, float time);
bool LiveStats_Probation_MoveToMatchHistory(const ControllerIndex_t controllerIndex, const char *gameModeString, ddlState_t *matchHistorySearchState, unsigned int *firstIndex, unsigned int *totalCount);
void LiveStats_GameHistory_ClearMatchStats(const ControllerIndex_t controllerIndex, const char *gamemode);
void LiveStats_Probation_ValidateProbationVersion(const ControllerIndex_t controllerIndex, eGameModes gamemode);
bool LiveStats_Probation_CheckInProbation(const ControllerIndex_t controllerIndex, eGameModes gamemode, bool report);
bool LiveStats_Probation_ShouldCheckProbation(const ControllerIndex_t controllerIndex, eGameModes gamemode);
float LiveStats_Probation_GetProbationPoints(const ControllerIndex_t controllerIndex, eGameModes gamemode, ddlState_t *matchHistorySearchState, unsigned int *probationMatchCount, unsigned int (*probationMatchs)[32]);
bool LiveStats_Probation_CheckGettingProbation(eGameModes a1, ControllerIndex_t a2, float controllerIndex, const ControllerIndex_t gamemode, eGameModes a5);
void LiveStats_Probation_ForgiveProbation(const ControllerIndex_t controllerIndex, eGameModes gamemode, ddlState_t *matchHistorySearchState, unsigned int *probationMatchCount, unsigned int (*probationMatchs)[32]);
void LiveStats_Probation_ReportProbationStats(const ControllerIndex_t controllerIndex, eGameModes gamemode);
bool LiveStats_Probation_CheckForProbation(double controllerIndex, float noPopups, const ControllerIndex_t a3, eGameModes gamemode, bool a5);
void LiveStats_Theater_IncrementStat(const ControllerIndex_t controllerIndex, playerStatsKeyIndex_t statKeyIndex);
void LiveStats_GameHistory_DumpMatchStats(const ControllerIndex_t controllerIndex, const char *gamemode);
void LiveStats_GameHistory_ClearProbation(const ControllerIndex_t controllerIndex, const char *gamemode);
void LiveStats_GameHistory_GiveProbation(const ControllerIndex_t controllerIndex, const char *gamemode);
void LiveStats_GameHistory_FinishMatch(ddlState_t *a1, const ControllerIndex_t controllerIndex);
void LiveStats_GameHistory_TimeoutMatch(ddlState_t *a1, const ControllerIndex_t controllerIndex);
int LiveStats_GetTotalMatchesPlayed(const ControllerIndex_t controllerIndex);
void LiveStats_DumpMatchStatsCmd();
void LiveStats_ClearMatchStatsCmd();
void LiveStats_ClearProbationCmd();
void LiveStats_GiveProbationCmd();
void LiveStats_SetLobbyPopup(const ControllerIndex_t controllerIndex, const char *menuName);
char LiveStats_ValidateStatsBackup(const ControllerIndex_t controllerIndex);
bool LiveStats_MoveToSkillAndVariance(ddlState_t *skillState, ddlState_t *varianceState);
bool LiveStats_GetSkillAndVariance(const ControllerIndex_t controllerIndex, float *skill, float *variance);
void LiveStats_StoreOriginalValues(const ControllerIndex_t controllerIndex, unsigned __int8 *statsBuffer);
void LiveStats_CheckVsOriginalValues(const ControllerIndex_t controllerIndex);
statsValidation_t LiveStats_AreStatsDeltasValid(const ControllerIndex_t controllerIndex, statsLocation initialStats, statsLocation currentStats);
void LiveStats_CheckScoreInfoTable();
void LiveStats_ResetAttachmentChallenges(const ControllerIndex_t controllerIndex, const char *statName, const char *statType);
void LiveStats_ResetGroupChallenges(const ControllerIndex_t controllerIndex, const char *statName, const char *statType, challengeTableRow_t *challengeRow);
void LiveStats_ResetGlobalChallenges(const ControllerIndex_t controllerIndex, const char *statName, const char *statType, challengeTableRow_t *challengeRow);
void LiveStats_ResetWeaponChallenges(const ControllerIndex_t controllerIndex, const char *statName, const char *statType, challengeTableRow_t *challengeRow);
void LiveStats_PushMatchesPlayedMilestonesToElite(const ControllerIndex_t controllerIndex);
void LiveStats_IncrementPlayerLeanMatchesCount(const ControllerIndex_t controllerIndex);
unsigned int LiveStats_GetClanTagFeature(const ControllerIndex_t controllerIndex);
char LiveStats_SetClanTagText(const ControllerIndex_t controllerIndex, const char *clanName);
int LiveStats_GetPrestige(const ControllerIndex_t controllerIndex);
BOOL LiveStats_GetGametypeBan(const ControllerIndex_t controllerIndex);
int LiveStats_GetCurrency(const ControllerIndex_t controllerIndex);
int LiveStats_GetIntZombieStatByKey(const ControllerIndex_t controllerIndex, zombieStatsKeyIndex_t keyIndex);
int LiveStats_GetZombieWeightedRoundsPlayed(const ControllerIndex_t controllerIndex);
int LiveStats_GetZombieWeightedDowns(const ControllerIndex_t controllerIndex);
int LiveStats_GetZombieTimePlayedTotal(const ControllerIndex_t controllerIndex);
int LiveStats_GetIntPlayerStatByLocationGameType(const ControllerIndex_t controllerIndex, const char *startLocation, const char *gameType, const char *statName);
void LiveStats_TrackSpending(const ControllerIndex_t controllerIndex, int currencyAmount);
char LiveStats_SpendCurrency(int a1, ControllerIndex_t a2, const ControllerIndex_t controllerIndex, int currencyAmount, pointsSpent_t reasonType, int reasonIndex);
bool LiveStats_DoXUIDsMatch(const ControllerIndex_t controllerIndex);
void LiveStats_InitStatsBuffer(unsigned int a1, statsLocation a2, const ControllerIndex_t controllerIndex, statsResetReason_t reason);
void LiveStats_ResetStats(unsigned int a1, const ControllerIndex_t controllerIndex, bool versionChanged, statsResetReason_t reason);
char LiveStats_GetConsoleDetails(unsigned __int8 *consoleLocalIP, unsigned __int8 *consoleExternalIP);
void LiveStats_CheckUnlockTokens(const ControllerIndex_t controllerIndex);
void LiveStats_DoSecurityChecks(const ControllerIndex_t controllerIndex);
void LiveStats_DoSecurityChecksCmd();
void LiveStats_PrestigeStatsResetAllCmd();
void LiveStats_PrestigeRespecCmd();
char *LiveStats_MoveToGameTypeStatPath(ddlState_t *resultState, const char *statName, const char *statType, int gameTypeIndex, bool isGroup);
void LiveStats_SetRankXP(unsigned int a1, ControllerIndex_t controllerIndex, unsigned int rankXP);
void LiveStats_SetRankXPCmd(unsigned int a1);
void __cdecl LiveStats_SetZombieRank(ControllerIndex_t controllerIndex, unsigned int rank, unsigned int daysPlayed);
void LiveStats_SetZombieRankCmd();
void LiveStats_SetStatChangedInternal(const ControllerIndex_t controllerIndex, unsigned __int8 *statsMsg, int msgLen, int isMoreComing);
void LiveStats_SetStatChanged(const ControllerIndex_t controllerIndex, const char *hexMsg, int isMoreComing);
void LiveStats_SetStatChangedNoCache(const ControllerIndex_t controllerIndex, const char *hexMsg, int isMoreComing);
void LiveStats_PreGame(unsigned int a1, const ControllerIndex_t controllerIndex);
void LiveStats_MakeStableStatsBuffer(const ControllerIndex_t controllerIndex);
void LiveStats_CopyFromSponsor(const ControllerIndex_t controllerIndex);
void LiveStats_ResetGametypeChallenges(const ControllerIndex_t controllerIndex, const char *statName, const char *statType, challengeTableRow_t *challengeRow);
int LiveStats_GetRank(const ControllerIndex_t controllerIndex);
int LiveStats_GetZombieLastDaysPlayed(const ControllerIndex_t controllerIndex);
bool LiveStats_SetLeaderboardCombinedRankZombie(const ControllerIndex_t controllerIndex);
void LiveStats_SetCheckSumFromServer(const char *checkSumMsg);
void LiveStats_PublishNews(const ControllerIndex_t controllerIndex);
void LiveStats_ShowStatsError(const ControllerIndex_t localControllerIndex);
void LiveStats_ValidateStats(const ControllerIndex_t controllerIndex);
void LiveStats_PrestigeResetChallenges(char *a1, const ControllerIndex_t controllerIndex);
int LiveStats_GetCurrentChallengeIndex(const ControllerIndex_t controllerIndex, int inputChallengeIndex, int itemIndex);
void LiveStats_GetCurrentchallengeRowCmd();
void LiveStats_CheckAchievements(const ControllerIndex_t controllerIndex);
char LiveStats_CompareStatsVsStableBuffer(const ControllerIndex_t controllerIndex, bool onlyCheckValidStats);
void LiveStats_PrestigeStatsResetCmd(unsigned int a1);
void LiveStats_CompareStatsVsStableBufferCmd();
void LiveStats_Init();

//t6/code/src_noserver/live/live_steam.cpp
bool LiveSteam_isVacAuthorized();
bool LiveSteam_IsInitialized();
unsigned __int64 LiveSteam_GetUserSteamIDAsXUID();
void LiveSteam_ShowStore(unsigned int appID);
void LiveSteam_ShowFriendsList(void *notthis);
int LiveSteam_GetAppID();
void LiveSteam_Shutdown();
void LiveSteam_Frame();
int Utf8SymbolSize(char utf8Byte1);
int LiveSteam_FilterPersonaName(char *utf8Name, bool asciionly);
void Utf8safe_strncpyz(char *dest, const char *src, int destsize);
BOOL LiveSteam_isValidAppId(unsigned int appId);
int LiveSteam_GetAppIdForContentPack(const int contentPack);
int LiveSteam_GetContentPackForSteamAppID(unsigned int steamAppID);
int LiveSteam_SetContentPack(const int contentPack);
void LiveSteam_Client_SteamDisconnect();
void __cdecl LiveSteam_PopOverlayForSteamID(unsigned __int64 steamID);
void LiveSteam_Init();
char *LiveSteam_FriendPersonaNameFromXuid(int a1, char *a2, unsigned __int64 xuid, char *buff, int size, bool asciionly);
unsigned int LiveSteam_Client_ConnectToSteamServer(unsigned __int64 serverID, const netadr_t *serverAddr, void *authBlob, unsigned int bufferSize);

//t6/code/src_noserver/live/live_steam_achievements.cpp
void LiveSteam_Achievements_Frame();
void LiveSteam_GiveAchievement(const char *achievementName);
void LiveSteam_Achievements_Shutdown();

//t6/code/src_noserver/live/live_steam_server.cpp
void SV_SteamAuthClientRequest(netadr_t to, unsigned __int64 serverSteamID);
int FindClient(unsigned __int64 liveUserID);
void RunClientChecks(const int clientNum);
// void LiveSteamServer::OnSteamServersConnected(LiveSteamServer *notthis, SteamServersConnected_t *pLogonSuccess);
// void LiveSteamServer::OnSteamServerConnectFailure(LiveSteamServer *notthis, SteamServerConnectFailure_t *pConnectFailure);
// void LiveSteamServer::OnSteamServersDisconnected(LiveSteamServer *notthis, SteamServersDisconnected_t *pLoggedOff);
// void LiveSteamServer::OnPolicyResponse(LiveSteamServer *notthis, GSPolicyResponse_t *pPolicyResponse);
// void LiveSteamServer::KickClientFromSteamGameServer(LiveSteamServer *notthis, CSteamID clientID, EDenyReason reason);
// void LiveSteamServer::OnGSClientApprove(LiveSteamServer *notthis, GSClientApprove_t *pGSClientApprove);
// void LiveSteamServer::OnGSClientDeny(LiveSteamServer *notthis, GSClientDeny_t *pGSClientDeny);
// void LiveSteamServer::OnGSClientKick(LiveSteamServer *notthis, GSClientKick_t *pGSClientKick);
unsigned int LiveSteam_Server_InitErroExceptionFilter(unsigned int code, _EXCEPTION_POINTERS *info);
void LiveSteam_Server_HandleInitError(const char *error);
void LiveSteam_Server_ClientSteamAuthentication(unsigned __int64 clientSteamID, netadr_t netAddr, void *authBlob, unsigned int authBlobSize);
unsigned int LiveSteam_Server_SetCurrentDlcAppID(unsigned int steamAppID);
void LiveSteam_Server_ClientSteamDisconnect(unsigned __int64 clientSteamID);
// void LiveSteamServer::~LiveSteamServer(LiveSteamServer *notthis);
// void LiveSteamServer::LiveSteamServer(LiveSteamServer *notthis, unsigned int ip);
void LiveSteam_Server_Shutdown();
void LiveSteam_Server_Init(const char *mapname);
// void LiveSteamServer::RunFrame(LiveSteamServer *notthis);
void LiveSteam_Server_Frame();

//t6/code/src_noserver/live/live_storage.cpp
void LiveStorage_CorrectStatsError(const char *msg);
void LiveStorage_VerifyCorrectStats(persistentStats *stats, statsLocation location);
persistentStats *LiveStorage_GetPersStatsBuffer(const ControllerIndex_t controllerIndex, statsLocation playerStatsLocation, bool verifyLocation);
persistentStats *LiveStorage_GetStatsBufferForDownload(statsLocation a1, const ControllerIndex_t controllerIndex, statsLocation playerStatsLocation, bool verifyLocation);
int LiveStorage_GetStatsBufferSize();
classSets_t *LiveStorage_GetClassSetsBuffer(const ControllerIndex_t controllerIndex);
bool LiveStorage_GetStatsChecksumValid(statsLocation a1, const ControllerIndex_t controllerIndex);
void LiveStorage_SetStatsChecksumValid(statsLocation a1, const ControllerIndex_t controllerIndex, statsLocation playerStatsLocation, bool isValid);
bool LiveStorage_AreStatsDDLValidated(statsLocation a1, const ControllerIndex_t controllerIndex);
void LiveStorage_SetStatsDDLValidated(statsLocation a1, const ControllerIndex_t controllerIndex, statsLocation playerStatsLocation, bool statsValidatedWithDDL);
void LiveStorage_StatsBackupFetchCompleted(const ControllerIndex_t controllerIndex);
bool LiveStorage_DoWeHaveStats(statsLocation a1, const ControllerIndex_t controllerIndex);
bool LiveStorage_DoWeHaveCurrentStats(const ControllerIndex_t controllerIndex);
bool LiveStorage_DoWeHaveAllStats(const ControllerIndex_t controllerIndex);
void LiveStorage_SetStatsFetched(statsLocation a1, const ControllerIndex_t localControllerIndex, statsLocation playerStatsLocation, bool isFetched);
void LiveStorage_DisableStatsUpload(const ControllerIndex_t localControllerIndex);
bool LiveStorage_IsStatsUploadDisabled(const ControllerIndex_t localControllerIndex);
EUserTier getTierForGamertag(const char *gamertag, unsigned __int64 xuid);
void LiveStorage_ParseUserTiers();
bool Live_CanGamertagUseRestrictedClanTag(const char *gamertag, unsigned __int64 xuid);
TaskRecord *LiveStorage_SetupNestedTask(const TaskDefinition *taskdef, ControllerIndex_t controllerIndex, TaskRecord *nestedTask, void *payload);
void LiveStorage_ResetFileInfo(dwFileOperationInfo *fileInfo);
void LiveStorage_UpdateFileTryData(fileRetryInfo *retryInfo);
char LiveStorage_TryFile(fileRetryInfo *retryInfo);
char LiveStorage_DeleteUserFileFailure(TaskRecord *task);
char LiveStorage_DeleteUserFileSuccess(TaskRecord *task);
char LiveStorage_WriteUserFileFailure(TaskRecord *task);
char LiveStorage_WriteUserFileSuccess(TaskRecord *task);
TaskRecord *LiveStorage_WriteDWUserFile(const ControllerIndex_t controllerIndex, dwFileOperationInfo *fileInfo, unsigned __int64 uid);
char LiveStorage_GetUserFileFailure(TaskRecord *task);
TaskRecord *LiveStorage_ReadDWFile(const ControllerIndex_t controllerIndex, dwFileOperationInfo *fileInfo);
TaskRecord *LiveStorage_ReadDWFileByUserID(const ControllerIndex_t controllerIndex, dwFileOperationInfo *fileInfo, unsigned __int64 xuidLocal);
void LiveStorage_CopyClassSetsFromSponsor(const ControllerIndex_t controllerIndex, const ControllerIndex_t sponsorIndex);
void LiveStorage_SetClassSetsWriteNeeded(const ControllerIndex_t controllerIndex, bool writeNeeded);
bool LiveStorage_WriteClassSetsFailure(TaskRecord *task);
void LiveStorage_TrackUsedClassSets(const ControllerIndex_t controllerIndex);
TaskRecord *LiveStorage_WriteClassSets(const ControllerIndex_t controllerIndex, char *customFileName);
int LiveStorage_PlayerStatsFileNotFound(const ControllerIndex_t controllerIndex, void *data);
char LiveStorage_KeyArchiveWriteComplete(TaskRecord *task);
char LiveStorage_KeyArchiveWriteFailed(TaskRecord *task);
char LiveStorage_KeyArchiveReadComplete(TaskRecord *task);
char LiveStorage_KeyArchiveReadFailed(TaskRecord *task);
TaskRecord *LiveStorage_GetXPGroupsKeyArchive(ControllerIndex_t controllerIndex, const char **inputKeys, int *outRatings, int count);
bool LiveStorage_GetServerTimeComplete();
char LiveStorage_GetServerTimeFailed();
int LiveStorage_GetUTC();
int LiveStorage_GetUTCOffset();
bool LiveStorage_IsTimeSynced();
void LiveStorage_WriteMetPlayerListSuccessful(const ControllerIndex_t controllerIndex);
TaskRecord *LiveStorage_WriteMetPlayerList(const ControllerIndex_t controllerIndex, const char *fileName, unsigned __int8 *buffer, int sizeOfBuffer);
int LiveStorage_OtherPlayerStatsFileNotFound(const ControllerIndex_t controllerIndex, void *data);
TaskRecord *LiveStorage_ReadCommonStats(const ControllerIndex_t controllerIndex, bool silent, statsLocation location, const TaskDefinition *taskDef, dwFileOperationInfo *fileInfo);
int LiveStorage_CalculateParity(unsigned __int8 *inBuffer, unsigned __int8 *outBuffer, int inBufferSize, int outBufferSize);
void LiveStorage_CheckParityBits(unsigned __int8 *buffer, int bufferSize, int *parityBuffer, int parityBufferSize);
void LiveStorage_AppendParityToStats(unsigned __int8 *tempStatsBuffer, int bufferSize, dwFileOperationInfo *fileInfo);
TaskRecord *LiveStorage_WriteBackupStatsInternal(const ControllerIndex_t controllerIndex, dwFileOperationInfo *fileInfo, const TaskDefinition *taskdef);
void __cdecl LiveStorage_BackupCorruptedStatsDecompressError(const ControllerIndex_t controllerIndex, unsigned __int8 *buffer, int bufferSize, char *fileName);
void LiveStorage_SetAllStatsNotFetched(const ControllerIndex_t controllerIndex);
fileShareLocation LiveStorage_FileShare_GetCurrentHTTPLocation(ControllerIndex_t controllerIndex);
void LiveStorage_FileShare_GetDownloadProgress(const ControllerIndex_t controllerIndex, unsigned int *bytes, float *dataRate);
void LiveStorage_FileShare_GetUploadProgress(const ControllerIndex_t controllerIndex, unsigned int *bytes, float *dataRate);
BOOL LiveStorage_FileShare_IsReady(const ControllerIndex_t controllerIndex, bool allowRead);
void LiveStorage_FileShare_AbortOperation(const ControllerIndex_t controllerIndex, fileShareLocation location);
TaskRecord *LiveStorage_FileShare_ReadListing(const ControllerIndex_t controllerIndex, fileshareListingInfo_t *info);
char LiveStorage_FileShare_ReadListingFailure(TaskRecord *task);
int LiveStorage_FileShareSortComparator_MostRecent(const void *arg0, const void *arg1);
void LiveStorage_FileShare_LoadBlockSuccessAction(const ControllerIndex_t controllerIndex, dwFileShareDescriptorsTask *fsTask);
void LiveStorage_FileShare_DownloadFile_f();
char LiveStorage_FileShare_SearchFailure(TaskRecord *task);
unsigned int LiveStorage_FileShare_ReadFileData(void *data, unsigned int dataSize, dwFileShareReadFileTask *fileTask);
unsigned int LiveStorage_FileShare_GetDownloadingFileTotalSize(const ControllerIndex_t controllerIndex);
ControllerIndex_t LiveStorage_FileShare_GetUploadingFileTotalSize(const ControllerIndex_t controllerIndex);
// unsigned int fileShareDownloadInterceptor::handleDownload(fileShareDownloadInterceptor *notthis, void *data, unsigned int dataSize);
char LiveStorage_FileShare_ReadFileFailure(TaskRecord *task);
char LiveStorage_FileShare_ReadFileSuccess(TaskRecord *task);
char *LiveStorage_GetDWDownloadBuffer();
int LiveStorage_GetDWDownloadBufferSize();
unsigned int LiveStorage_FileShare_WriteFileData(void *data, unsigned int dataSize, unsigned int bytesUploaded, dwFileShareWriteFileTask *fileTask);
// unsigned int fileShareUploadInterceptor::handleUpload(fileShareUploadInterceptor *notthis, void *data, unsigned int dataSize, unsigned int bytesUploaded);
BOOL LiveStorage_FileShare_ReadFileIsInProgress(const ControllerIndex_t controllerIndex);
BOOL LiveStorage_FileShare_WriteFileIsInProgress(const ControllerIndex_t controllerIndex);
char LiveStorage_FileShare_WriteFileFailure(TaskRecord *task);
char LiveStorage_FileShare_WriteFileSuccess(TaskRecord *task);
BOOL LiveStorage_FileShare_ParseDownloadedMatchData(const ControllerIndex_t controllerIndex, unsigned __int64 fileID, unsigned __int8 *buffer, int bufferSize);
TaskRecord *LiveStorage_FileShare_WriteSummary(const ControllerIndex_t controllerIndex, fileShareWriteSummaryInfo *summaryFileInfo, bool showSuccess);
char LiveStorage_FileShare_WriteSummaryFailure(TaskRecord *task);
char LiveStorage_FileShare_WriteSummarySuccess(TaskRecord *task);
BOOL LiveStorage_FileShare_ReadSummaryInProgress();
TaskRecord *LiveStorage_FileShare_ReadSummary(const char *a1, const ControllerIndex_t controllerIndex, unsigned __int64 fileID, int summarySize, fileShareLocation location, void (*successCallback)(const ControllerIndex_t, unsigned __int64), void (*failureCallback)(const ControllerIndex_t));
char LiveStorage_FileShare_ReadSummaryFailure(TaskRecord *task);
char LiveStorage_FileShare_ReadSummarySuccess(TaskRecord *task);
TaskRecord *LiveStorage_FileShare_ReadMetaDataByID(const char *a1, const ControllerIndex_t controllerIndex, bdFileID *fileIDs, int numFiles, bdFileMetaData *outDescriptors, fileShareLocation location, void (*successCallback)(const ControllerIndex_t), void (*failureCallback)(const ControllerIndex_t));
char LiveStorage_FileShare_ReadMetaDataByIDFailure(TaskRecord *task);
char LiveStorage_FileShare_ReadMetaDataByIDSuccess(TaskRecord *task);
TaskRecord *LiveStorage_FileShare_RemoveFile(const ControllerIndex_t controllerIndex, unsigned int fileSlot, void (*successCallback)(const ControllerIndex_t, int), void (*failureCallback)(const ControllerIndex_t));
char LiveStorage_FileShare_RemoveFileFailure(TaskRecord *task);
char LiveStorage_FileShare_RemoveFileSuccess(TaskRecord *task);
TaskRecord *LiveStorage_FileShare_TransferFile(const ControllerIndex_t controllerIndex, bdFileMetaData *descriptor, fileShareLocation location, unsigned int userSlot, void (*successCallback)(const ControllerIndex_t), void (*failureCallback)(const ControllerIndex_t));
char LiveStorage_FileShare_TransferFileFailure(TaskRecord *task);
char LiveStorage_FileShare_TransferFileSuccess(TaskRecord *task);
char LiveStorage_FileShare_ReadTopRatedFailure(TaskRecord *task);
bool LiveStorage_UserFileListAvailable(const ControllerIndex_t controllerIndex);
void LiveStorage_AssertDWConnectionCmd();
void __cdecl LiveStorage_GeneratePopulationDataCmd();
void LiveStorage_FakeComErrorCmd();
void LiveStorage_CopyStatsBuffer(statsLocation a1, const ControllerIndex_t controllerIndex, const ControllerIndex_t fromControllerIndex);
char LiveStorage_VerifyStatsPresent(statsLocation a1, const ControllerIndex_t controllerIndex, statsLocation playerStatsLocation, const char *file, const char *func, int line);
persistentStats *__cdecl LiveStorage_GetStatsBufferWithCaller(const ControllerIndex_t controllerIndex, const char *file, const char *func, int line, statsLocation playerStatsLocation, bool verifyLocation);
bool LiveStorage_GetStatsWriteNeeded(statsLocation a1, const ControllerIndex_t controllerIndex, statsLocation location);
void LiveStorage_SetStatsWriteNeeded(statsLocation a1, const ControllerIndex_t controllerIndex, bool isWriteNeeded, statsLocation location);
int LiveStorage_ValidateWithDDL(ControllerIndex_t controllerIndex, statsLocation location);
void LiveStorage_FetchRequiredFiles(const ControllerIndex_t controllerIndex);
void LiveStorage_GetUserFileDecompressError(TaskRecord *task);
char LiveStorage_GetUserFileSuccess(TaskRecord *task);
char LiveStorage_IsPublicStatsCorrectState(const ControllerIndex_t controllerIndex, statsLocation location);
void LiveStorage_ResetClassSets(const ControllerIndex_t controllerIndex);
int LiveStorage_ClassSetsFileNotFound(void *notthis);
void LiveStorage_ReadClassSetsSuccessful(const ControllerIndex_t controllerIndex, void *data);
TaskRecord *LiveStorage_ReadClassSets(const ControllerIndex_t controllerIndex);
void LiveStorage_ReadOtherPlayerStatsSuccessful(statsLocation a1, const ControllerIndex_t controllerIndex);
void LiveStorage_CheckEmptyStats(const ControllerIndex_t controllerIndex, int decompressedSize);
TaskRecord *LiveStorage_SyncTime(ControllerIndex_t controllerIndex);
TaskRecord *LiveStorage_ReadOtherPlayerStats(const ControllerIndex_t controllerIndex, unsigned __int64 playerXuid);
TaskRecord *LiveStorage_WriteStats(const ControllerIndex_t controllerIndex, bool backup, statsLocation location, const TaskDefinition *taskDef, dwFileOperationInfo *fileInfo);
bool LiveStorage_WritePlayerStatsFailure(TaskRecord *task);
TaskRecord *__cdecl LiveStorage_WritePlayerStats(const ControllerIndex_t controllerIndex);
void LiveStorage_WriteBackupStats(char *a1, const ControllerIndex_t controllerIndex);
void LiveStorage_BackupStatsToFile(const ControllerIndex_t controllerIndex, const char *filename, unsigned __int8 *parityBits);
char LiveStorage_FileShare_ReadListingSuccess(TaskRecord *task);
char LiveStorage_FileShare_LoadBlockFailure(TaskRecord *task);
char LiveStorage_FileShare_LoadBlockSuccess(TaskRecord *task);
char LiveStorage_FileShare_SearchSuccess(TaskRecord *task);
char LiveStorage_FileShare_ReadTopRatedSuccess(TaskRecord *task);
void LiveStorage_UploadStatsForController(const ControllerIndex_t controllerIndex);
void LiveStorage_UploadStats();
void LiveStorage_WriteBackupStatsCmd();
void LiveStorage_GetFriendStatsCmd();
char LiveStorage_GetUserFileListSuccess(TaskRecord *task);
char LiveStorage_GetUserFileListFailure(TaskRecord *task);
bdFileInfo *LiveStorage_UserFileListGetFileDetails(const ControllerIndex_t controllerIndex, const char *fileName);
void LiveStorage_RestoreStatsFromBackup(const ControllerIndex_t localControllerIndex);
void LiveStorage_RestoreCorrectPublicStatsState(statsLocation a1, const ControllerIndex_t controllerIndex);
void LiveStorage_StatsBackupReadSuccessful(const ControllerIndex_t controllerIndex, void *data);
int LiveStorage_StatsBackupFileNotFound(const ControllerIndex_t controllerIndex, void *data);
void LiveStorage_ReadPlayerStatsSuccessful(const ControllerIndex_t controllerIndex, void *data);
TaskRecord *LiveStorage_ReadStatsBackup(const ControllerIndex_t controllerIndex);
TaskRecord *LiveStorage_ReadPlayerStats(dwFileOperationInfo *a1, const ControllerIndex_t controllerIndex, bool validate);
void LiveStorage_ReadStats(ControllerIndex_t a1, const ControllerIndex_t controllerIndex, dwFileOperationInfo *validate);
TaskRecord *LiveStorage_FileShare_LoadPage(const char *a1, const ControllerIndex_t controllerIndex, int numFiles, bdFileID *fileIDs, fileShareLocation location, bdFileMetaData *outDescriptors, int *outDescriptorCount, bool shouldSort, void (*successCallback)(const ControllerIndex_t), void (*failureCallback)(const ControllerIndex_t));
// TaskRecord *LiveStorage_FileShare_ReadFile(const char *a1@<ebx>, const char *a2, const ControllerIndex_t controllerIndex, fileShareReadFileInfo *fileInfo);
TaskRecord *LiveStorage_FileShare_WriteFile(const char *a1, const char *a2, const ControllerIndex_t controllerIndex, fileShareWriteFileInfo *writeFileInfo);
void LiveStorage_ReadStatsBackupCmd();
void LiveStorage_RestoreStatsFromBackupCmd();
char LiveStorage_Init();
char LiveStorage_WaitOnStats(ControllerIndex_t controllerIndex);

//t6/code/src_noserver/live/live_storage_pub.cpp
bool LiveStorage_DoWeHavePlaylists();
bool LiveStorage_DoWeHaveContracts();
int LiveStorage_GetFFOTDVersion();
bool LiveStorage_DoWeHaveLeagues();
const char *LiveStorage_GetOnlineWADFilename();
TaskRecord *LiveStorage_GetFFOTDTimeStamp(ControllerIndex_t controllerIndex);
TaskRecord *LiveStorage_GetOnlineWADTimestamp(ControllerIndex_t controllerIndex);
void LiveStorage_CheckWADTimestampRequired(ControllerIndex_t controllerIndex);
BOOL LiveStorage_DecompressBuffer(unsigned __int8 *compressedBuffer, unsigned int compressedSize, unsigned __int8 *uncompressedBuffer, unsigned int uncompressedSize);
void LiveStorage_ParseOnlineData();
char LiveStorage_WaitForContentMounting();
char LiveStorage_WaitForGhostLBFetching();
void LiveStorage_FetchOnlineWADSuccessful(const ControllerIndex_t controllerIndex);
int LiveStorage_PublisherStorageFetchOnlineWADNotFound();
TaskRecord *LiveStorage_FetchOnlineWAD(const ControllerIndex_t controllerIndex);
bool LiveStorage_DoWeHaveOnlineWAD();
void LiveStorage_RefetchOnlineWAD();
bool LiveStorage_CompletedPlaylistPopulation();
unsigned __int8 *LiveStorage_GetPlaylistPopulationBuffer();
int LiveStorage_PublisherStorageFetchFFOTDNotFound(const ControllerIndex_t controllerIndex);
void LiveStorage_FetchFFOTDChunkSuccessful(const ControllerIndex_t controllerIndex);
TaskRecord *LiveStorage_FetchFFOTDChunk(ControllerIndex_t controllerIndex, int part);
TaskRecord *LiveStorage_FetchFFOTD(const ControllerIndex_t controllerIndex);
bool LiveStorage_DoWeHaveFFOTD();
unsigned __int8 *LiveStorage_GetFFOTDBuffer();
unsigned int LiveStorage_GetFFOTDSize();
bool LiveStorage_ValidateFFOTD();
void LiveStorage_ExecFFOTDSettings();
void LiveStorage_HandleFFOTDTasks();
void LiveStorage_SetFFOTDVersion_f();
ecc_key *LiveStats_GetPublicKey();
ecc_key *LiveStats_GetPrivateKey();
BOOL LiveStorage_SignedStats_InitPublicKey(const void *buffer, int size);
BOOL LiveStorage_SignedStats_InitPrivateKey(const void *buffer, int size);
int LiveStorage_SignedStatsKeyFileNotFound(const ControllerIndex_t controllerIndex, void *data);
void LiveStorage_SignedStatsKeyFetchSuccessful(const ControllerIndex_t controllerIndex, void *data);
void LiveStorage_FetchSignedStatsKeys(const ControllerIndex_t controllerIndex);
char LiveStorage_DoWeHaveSignedStatsKeys();
char LiveStorage_GetOnlineWADTimestampSuccess(TaskRecord *task);
char LiveStorage_GetOnlineWADTimestampFailure(TaskRecord *task);
char LiveStorage_GetFFOTDTimeStampSuccess(TaskRecord *task);
char Live_StorageGetFFOTDTimeStampFailure(TaskRecord *task);
void LiveStorage_ProcessOnlineWAD();
void LiveStorage_HandlePublisherStorageTasks();

//t6/code/src_noserver/live/live_storage_streambuff.cpp
bool LiveStorage_StreamBuff_Init(streamBuffer_t *streamBuff, unsigned __int8 *buffer, int bufferSize, void *userData, int userDataSize);
int LiveStorage_StreamBuff_Write(streamBuffer_t *streamBuff, unsigned __int8 *data, int dataSize);

//t6/code/src_noserver/live/live_storage_win.cpp
dwFileOperationInfo *SV_GetFreeFileOp();
void SV_DumpFileOps();
void SV_UseFileOp();
void SV_FreeFileOp();
void CL_GetXP_f();
void LiveStorage_Init_Platform();

//t6/code/src_noserver/live/live_tracker.cpp
unsigned int LiveTracker_GetColType(trackerColumn_e col);
int LiveTracker_SetItem(int queuePos, trackerColumn_e col, unsigned __int64 ent, int val);
int LiveTracker_GetColumnByName(const char *name);
int __cdecl LiveTracker_WriteByID(trackerColumn_e col, unsigned __int64 ent, int val);
const StringTable *LiveTracker_WriteByName(const char *colName, unsigned __int64 ent, int val);
BOOL LiveTracker_WriteForAllLocalUsers(trackerColumn_e col, int val);
BOOL LiveTracker_WriteForUserAndHost(const ControllerIndex_t controllerIndex, trackerColumn_e userCol, trackerColumn_e hostCol, int val);
void LiveTracker_UpdateCmd();
void LiveTracker_ReportUser();
void LiveTracker_StressTestCmd();
void LiveTracker_Init();

//t6/code/src_noserver/live/live_twitch.cpp
char LiveTwitch_IsRegisteredSuccess(TaskRecord *task);
char LiveTwitch_IsRegisteredFailure(TaskRecord *task);
char LiveTwitch_GetAccountSuccess(TaskRecord *task);
char LiveTwitch_GetAccountFailure(TaskRecord *task);
void LiveTwitch_ClearAccount(const ControllerIndex_t localControllerIndex);
TaskRecord *LiveTwitch_RegisterAccount(ControllerIndex_t localControllerIndex, const char *accountName, const char *authToken);
char LiveTwitch_RegisterAccountSuccess(TaskRecord *task);
void LiveTwitch_PrintError(ControllerIndex_t controllerIndex, const char *eventString, bdLobbyErrorCode error);
char LiveTwitch_UnregisterAccountSuccess(TaskRecord *task);
char LiveTwitch_UnregisterAccountFailure(TaskRecord *task);
void LiveTwitch_Register_f();
void LiveTwitch_UnRegister_f();
char LiveTwitch_RegisterAccountFailure(bdLobbyErrorCode a1, TaskRecord *task);
void LiveTwitch_Init();

//t6/code/src_noserver/live/live_twitter.cpp
char LiveTwitter_GetAccountSuccess(TaskRecord *task);
char LiveTwitter_GetAccountFailure(TaskRecord *task);
void LiveTwitter_ClearAccount(const ControllerIndex_t localControllerIndex);
char LiveTwitter_RegisterAccountSuccess(TaskRecord *task);
void LiveTwitter_PrintError(ControllerIndex_t controllerIndex, const char *eventString, bdLobbyErrorCode error);
char LiveTwitter_UnregisterAccountSuccess(TaskRecord *task);
char LiveTwitter_UnregisterAccountFailure(TaskRecord *task);
char LiveTwitter_PostSuccess(TaskRecord *task);
char LiveTwitter_GetInfoSuccess(TaskRecord *task);
char LiveTwitter_GetInfoFailure(TaskRecord *task);
char LiveTwitter_SearchFailure(TaskRecord *task);
char LiveTwitter_RegisterAccountFailure(bdLobbyErrorCode a1, TaskRecord *task);
char LiveTwitter_PostFailure(bdLobbyErrorCode a1, TaskRecord *task);
char LiveTwitter_SearchSuccess(TaskRecord *task);

//t6/code/src_noserver/live/live_voice.cpp
int Voice_FindUser(const SessionData *session, const unsigned __int64 xuid);
char Voice_UnregisterRemotePlayer(SessionData *session, const ClientNum_t slot);
int Live_GetConnectedPlayerList(const SessionData *session, unsigned __int64 *playerList);
int Voice_IncomingVoiceData(SessionData *session, ClientNum_t clientNum, unsigned __int8 *data, int size);
int Voice_IsMemberMuted(ControllerIndex_t localControllerIndex, const unsigned __int64 playerXuid);
void Voice_MuteMemberByXuid(const unsigned __int64 playerXuid);
void Voice_UnmuteMemberByXuid(const unsigned __int64 playerXuid);
int Voice_GetTalkingCount(SessionData *session, const ControllerIndex_t localControllerIndex);
void Voice_ClearRemoteTalkers(SessionData *session);
void Voice_EnableMicIfAllowed(SessionData *session);
char Voice_RegisterRemotePlayer(ControllerIndex_t localControllerIndex, SessionData *session, const unsigned __int64 player, const ClientNum_t clientNum);

//t6/code/src_noserver/live/live_vote.cpp
dwVoteCategory_e LiveVote_History_FileshareToVoteCategory(int fileshareCategory);
int LiveVote_History_GetEntryLinear(int startIndex, unsigned __int64 entityID, dwVoteCategory_e category);
int LiveVote_History_GetEntry(const ControllerIndex_t localControllerIndex, dwVoteCategory_e category, unsigned __int64 entityToFind);
int LiveVote_History_SortComparator(const void *a, const void *b);
void LiveVote_History_Sort();
void LiveVote_History_RecordVote(dwVoteCategory_e a1, const ControllerIndex_t localControllerIndex, unsigned __int64 entity, dwVoteCategory_e category, dwVote_e vote);
int LiveVote_History_GetVoteForEntity(dwVoteCategory_e a1, ControllerIndex_t a2, const ControllerIndex_t localControllerIndex, unsigned __int64 entity, dwVoteCategory_e category);
void LiveVote_RecentlyLiked_Build(const ControllerIndex_t localControllerIndex);
void LiveVote_RecentlyLiked_Remove(const ControllerIndex_t localControllerIndex, unsigned __int64 entity, dwVoteCategory_e category);
void LiveVote_RecentlyLiked_Add(const ControllerIndex_t localControllerIndex, unsigned __int64 entity, dwVoteCategory_e category);
char __cdecl LiveVote_Task_SubmitVoteSuccess(TaskRecord *task);
char LiveVote_Task_SubmitVoteFailure(TaskRecord *task);
TaskRecord *LiveVote_Task_SubmitVote(const ControllerIndex_t localControllerIndex, unsigned __int64 entity, dwVoteCategory_e category, dwVote_e vote);
char LiveVote_Task_DownloadHistoryFailure(TaskRecord *task);
void __cdecl LiveVote_SubmitCmd(dwVote_e vote);
void LiveVote_SubmitLikeCmd();
void LiveVote_SubmitDislikeCmd();
void LiveVote_GetHistoryCmd();
void LiveVote_GetVoteCmd();
void LiveVote_FillVoteHistoryCmd();
void LiveVote_Init();
char LiveVote_Task_DownloadHistorySuccess(TaskRecord *task);

//t6/code/src_noserver/live/live_win.cpp
char IsServerRunning();
SessionData *Live_GetCurrentSession();
char *Live_ControllerIndex_GetClientName(const ControllerIndex_t controllerIndex);
char *Live_ControllerIndex_GetXuidString(const ControllerIndex_t controllerIndex);
int CL_ControllerIndex_GetSignInState(ControllerIndex_t controllerIndex);
int CL_GetFirstActiveSignedInControllerIndex();
void Live_FakeDWDisconnect_f();
void Live_TestNotification_f();
void Live_UpdateInfoForInGameList_f();
void Live_InitPlatform();
char Live_XUIDIsLocalPlayer(const unsigned __int64 player);
ControllerIndex_t Live_GetControllerFromXUID(const unsigned __int64 player);
void Live_GiveAchievement(ControllerIndex_t localControllerIndex, const char *achievementName);
bool Live_AreWeAcceptingInvite();
void Live_AcceptInvite(ControllerIndex_t controllerIndex, InviteMessage *message, unsigned __int64 fromXuid);
char Live_UserGetName(ControllerIndex_t controllerIndex, char *buf, const int bufsize);
bool Live_UserSignedInToLive(const ControllerIndex_t controllerIndex);
EUserTier Live_GetTier(ControllerIndex_t controllerIndex);
void Live_SetTier(ControllerIndex_t controllerIndex, EUserTier tier);
bool Live_IsSystemUiActive();
bool Live_ShowFriendsList(void *notthis);
int Live_GetUploadSpeed();
char Live_BandwidthTestSuccess(TaskRecord *task);
char Live_BandwidthTestFailure(TaskRecord *task);
int Live_RunBandwidthTest(TaskRecord *task);
bool Live_QoSProbeEarlyComplete(dwQoSMultiProbeListener *listener);
void Live_EstimateQoSPercentage(dwQoSMultiProbeListener *listener);
char Live_QoSProbeSuccess(TaskRecord *task);
char Live_QoSProbeFailure(TaskRecord *task);
void Live_CleanUpQoSProbes();
BOOL Live_QoSInProgress();
void Live_InitSigninState();
char *JoinMessageReplyCriteriaError(JoinSessionMessage *message);
char Live_AreWeJoinable(bool fromInvite, e_JoinRejectionReason *reason);
char Live_ShowPlayerProfile(ControllerIndex_t localControllerIndex, unsigned __int64 xuid);
char Live_IsUserBlocked(ControllerIndex_t controllerIndex, unsigned __int64 xuid);
bdNATType Live_GetLocalNatType();
LocalTaskState Live_RunQoSProbe(TaskRecord *task);
void Live_StartQoSProbe(ControllerIndex_t localControllerIndex, int numXenons, XSESSION_INFO *xenonsInfo);
void Live_SendJoinInfo(ControllerIndex_t controllerIndex, unsigned __int64 recepient, JoinSessionMessage joinRequestMessage);
void Live_JoinMessageAction(ControllerIndex_t localControllerIndex, JoinSessionMessage message, unsigned __int64 from);
char Live_ProcessFriendInstantMessage(unsigned __int64 senderID, const ControllerIndex_t destIndex, msg_t *msg);

//t6/code/src_noserver/live/live_youtube.cpp
void LiveYouTube_ClearAccount(const ControllerIndex_t localControllerIndex);
char LiveYouTube_GetAccountSuccess(TaskRecord *task);
char LiveYouTube_GetAccountFailure(TaskRecord *task);
char LiveYouTube_GetUserTokenSuccess(TaskRecord *task);
char LiveYouTube_GetUserTokenFailure(TaskRecord *task);
TaskRecord *LiveYouTube_RegisterAccount(const ControllerIndex_t localControllerIndex);
char LiveYouTube_RegisterAccountSuccess(TaskRecord *task);
char LiveYouTube_RegisterAccountFailure(TaskRecord *task);
char LiveYouTube_UnregisterAccountSuccess(TaskRecord *task);
char LiveYouTube_UnregisterAccountFailure(TaskRecord *task);
TaskRecord *LiveYouTube_UploadVideo(const ControllerIndex_t localControllerIndex, unsigned __int64 fileID);
char LiveYouTube_UploadSuccess(TaskRecord *task);
char LiveYouTube_UploadFailure(TaskRecord *task);
void LiveYouTube_PrintError(ControllerIndex_t controllerIndex, bdLobbyErrorCode error);
void LiveYouTube_AuthReceived(const ControllerIndex_t localControllerIndex, bdLobbyErrorCode result);
bool LiveYouTube_IsAccountRegistered(const ControllerIndex_t localControllerIndex);
BOOL LiveYouTube_SetStat(const ControllerIndex_t controllerIndex, const char *statName, const char *statValue);
void LiveYouTube_SetViewerHighwater(const ControllerIndex_t controllerIndex, int numViewers);
void LiveYouTube_ParseDWKeys(unsigned __int8 *buffer);
void LiveYouTube_GetAccountCmd();
void LiveYouTube_TestSetStatCmd();
void LiveYouTube_TestGetStatCmd();
void LiveYouTube_TestSetViewerHighwaterCmd();
void LiveYouTube_RegisterAccountCmd();
void LiveYouTube_CancelCmd();
void LiveYouTube_UploadCmd();
TaskRecord *LiveYouTube_UnregisterAccount(const ControllerIndex_t localControllerIndex);
void LiveYouTube_UnregisterCmd();
void LiveYouTube_Init();

